// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: msggateway.proto

package msggatewaypb

import (
	sdkws "SuIM/proto/sdkws"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OnlinePushMsgReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgData       *sdkws.MsgData         `protobuf:"bytes,1,opt,name=msg_data,json=msgData,proto3" json:"msg_data,omitempty"`
	PushToUserId  string                 `protobuf:"bytes,2,opt,name=push_to_user_id,json=pushToUserId,proto3" json:"push_to_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlinePushMsgReq) Reset() {
	*x = OnlinePushMsgReq{}
	mi := &file_msggateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlinePushMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlinePushMsgReq) ProtoMessage() {}

func (x *OnlinePushMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlinePushMsgReq.ProtoReflect.Descriptor instead.
func (*OnlinePushMsgReq) Descriptor() ([]byte, []int) {
	return file_msggateway_proto_rawDescGZIP(), []int{0}
}

func (x *OnlinePushMsgReq) GetMsgData() *sdkws.MsgData {
	if x != nil {
		return x.MsgData
	}
	return nil
}

func (x *OnlinePushMsgReq) GetPushToUserId() string {
	if x != nil {
		return x.PushToUserId
	}
	return ""
}

type OnlinePushMsgResp struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Resp          []*SingleMsgToUserPlatform `protobuf:"bytes,1,rep,name=resp,proto3" json:"resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlinePushMsgResp) Reset() {
	*x = OnlinePushMsgResp{}
	mi := &file_msggateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlinePushMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlinePushMsgResp) ProtoMessage() {}

func (x *OnlinePushMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlinePushMsgResp.ProtoReflect.Descriptor instead.
func (*OnlinePushMsgResp) Descriptor() ([]byte, []int) {
	return file_msggateway_proto_rawDescGZIP(), []int{1}
}

func (x *OnlinePushMsgResp) GetResp() []*SingleMsgToUserPlatform {
	if x != nil {
		return x.Resp
	}
	return nil
}

type SingleMsgToUserResults struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	UserId        string                     `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Resp          []*SingleMsgToUserPlatform `protobuf:"bytes,2,rep,name=resp,proto3" json:"resp,omitempty"`
	OnlinePush    bool                       `protobuf:"varint,3,opt,name=online_push,json=onlinePush,proto3" json:"online_push,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleMsgToUserResults) Reset() {
	*x = SingleMsgToUserResults{}
	mi := &file_msggateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleMsgToUserResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleMsgToUserResults) ProtoMessage() {}

func (x *SingleMsgToUserResults) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleMsgToUserResults.ProtoReflect.Descriptor instead.
func (*SingleMsgToUserResults) Descriptor() ([]byte, []int) {
	return file_msggateway_proto_rawDescGZIP(), []int{2}
}

func (x *SingleMsgToUserResults) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SingleMsgToUserResults) GetResp() []*SingleMsgToUserPlatform {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *SingleMsgToUserResults) GetOnlinePush() bool {
	if x != nil {
		return x.OnlinePush
	}
	return false
}

type OnlineBatchPushOneMsgReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgData       *sdkws.MsgData         `protobuf:"bytes,1,opt,name=msg_data,json=msgData,proto3" json:"msg_data,omitempty"`
	PushToUserIds []string               `protobuf:"bytes,2,rep,name=push_to_user_ids,json=pushToUserIds,proto3" json:"push_to_user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineBatchPushOneMsgReq) Reset() {
	*x = OnlineBatchPushOneMsgReq{}
	mi := &file_msggateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineBatchPushOneMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineBatchPushOneMsgReq) ProtoMessage() {}

func (x *OnlineBatchPushOneMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineBatchPushOneMsgReq.ProtoReflect.Descriptor instead.
func (*OnlineBatchPushOneMsgReq) Descriptor() ([]byte, []int) {
	return file_msggateway_proto_rawDescGZIP(), []int{3}
}

func (x *OnlineBatchPushOneMsgReq) GetMsgData() *sdkws.MsgData {
	if x != nil {
		return x.MsgData
	}
	return nil
}

func (x *OnlineBatchPushOneMsgReq) GetPushToUserIds() []string {
	if x != nil {
		return x.PushToUserIds
	}
	return nil
}

type OnlineBatchPushOneMsgResp struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	SinglePushResult []*SingleMsgToUserResults `protobuf:"bytes,1,rep,name=single_push_result,json=singlePushResult,proto3" json:"single_push_result,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OnlineBatchPushOneMsgResp) Reset() {
	*x = OnlineBatchPushOneMsgResp{}
	mi := &file_msggateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineBatchPushOneMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineBatchPushOneMsgResp) ProtoMessage() {}

func (x *OnlineBatchPushOneMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineBatchPushOneMsgResp.ProtoReflect.Descriptor instead.
func (*OnlineBatchPushOneMsgResp) Descriptor() ([]byte, []int) {
	return file_msggateway_proto_rawDescGZIP(), []int{4}
}

func (x *OnlineBatchPushOneMsgResp) GetSinglePushResult() []*SingleMsgToUserResults {
	if x != nil {
		return x.SinglePushResult
	}
	return nil
}

type SingleMsgToUserPlatform struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResultCode     int64                  `protobuf:"varint,1,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`
	RecvId         string                 `protobuf:"bytes,2,opt,name=recv_id,json=recvId,proto3" json:"recv_id,omitempty"`
	RecvPlatformId int32                  `protobuf:"varint,3,opt,name=recv_platform_id,json=recvPlatformId,proto3" json:"recv_platform_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SingleMsgToUserPlatform) Reset() {
	*x = SingleMsgToUserPlatform{}
	mi := &file_msggateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleMsgToUserPlatform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleMsgToUserPlatform) ProtoMessage() {}

func (x *SingleMsgToUserPlatform) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleMsgToUserPlatform.ProtoReflect.Descriptor instead.
func (*SingleMsgToUserPlatform) Descriptor() ([]byte, []int) {
	return file_msggateway_proto_rawDescGZIP(), []int{5}
}

func (x *SingleMsgToUserPlatform) GetResultCode() int64 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *SingleMsgToUserPlatform) GetRecvId() string {
	if x != nil {
		return x.RecvId
	}
	return ""
}

func (x *SingleMsgToUserPlatform) GetRecvPlatformId() int32 {
	if x != nil {
		return x.RecvPlatformId
	}
	return 0
}

type GetUsersOnlineStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersOnlineStatusReq) Reset() {
	*x = GetUsersOnlineStatusReq{}
	mi := &file_msggateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersOnlineStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersOnlineStatusReq) ProtoMessage() {}

func (x *GetUsersOnlineStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersOnlineStatusReq.ProtoReflect.Descriptor instead.
func (*GetUsersOnlineStatusReq) Descriptor() ([]byte, []int) {
	return file_msggateway_proto_rawDescGZIP(), []int{6}
}

func (x *GetUsersOnlineStatusReq) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetUsersOnlineStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessResult []*SuccessResult       `protobuf:"bytes,1,rep,name=success_result,json=successResult,proto3" json:"success_result,omitempty"`
	FailedResult  []*FailedDetail        `protobuf:"bytes,2,rep,name=failed_result,json=failedResult,proto3" json:"failed_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersOnlineStatusResp) Reset() {
	*x = GetUsersOnlineStatusResp{}
	mi := &file_msggateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersOnlineStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersOnlineStatusResp) ProtoMessage() {}

func (x *GetUsersOnlineStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersOnlineStatusResp.ProtoReflect.Descriptor instead.
func (*GetUsersOnlineStatusResp) Descriptor() ([]byte, []int) {
	return file_msggateway_proto_rawDescGZIP(), []int{7}
}

func (x *GetUsersOnlineStatusResp) GetSuccessResult() []*SuccessResult {
	if x != nil {
		return x.SuccessResult
	}
	return nil
}

func (x *GetUsersOnlineStatusResp) GetFailedResult() []*FailedDetail {
	if x != nil {
		return x.FailedResult
	}
	return nil
}

type SuccessResult struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status               int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	DetailPlatformStatus []*SuccessDetail       `protobuf:"bytes,3,rep,name=detail_platform_status,json=detailPlatformStatus,proto3" json:"detail_platform_status,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SuccessResult) Reset() {
	*x = SuccessResult{}
	mi := &file_msggateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessResult) ProtoMessage() {}

func (x *SuccessResult) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessResult.ProtoReflect.Descriptor instead.
func (*SuccessResult) Descriptor() ([]byte, []int) {
	return file_msggateway_proto_rawDescGZIP(), []int{8}
}

func (x *SuccessResult) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SuccessResult) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SuccessResult) GetDetailPlatformStatus() []*SuccessDetail {
	if x != nil {
		return x.DetailPlatformStatus
	}
	return nil
}

type SuccessDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlatformId    int32                  `protobuf:"varint,1,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	ConnId        string                 `protobuf:"bytes,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	IsBackground  bool                   `protobuf:"varint,3,opt,name=is_background,json=isBackground,proto3" json:"is_background,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessDetail) Reset() {
	*x = SuccessDetail{}
	mi := &file_msggateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessDetail) ProtoMessage() {}

func (x *SuccessDetail) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessDetail.ProtoReflect.Descriptor instead.
func (*SuccessDetail) Descriptor() ([]byte, []int) {
	return file_msggateway_proto_rawDescGZIP(), []int{9}
}

func (x *SuccessDetail) GetPlatformId() int32 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *SuccessDetail) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *SuccessDetail) GetIsBackground() bool {
	if x != nil {
		return x.IsBackground
	}
	return false
}

func (x *SuccessDetail) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type FailedDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailedDetail) Reset() {
	*x = FailedDetail{}
	mi := &file_msggateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailedDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailedDetail) ProtoMessage() {}

func (x *FailedDetail) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailedDetail.ProtoReflect.Descriptor instead.
func (*FailedDetail) Descriptor() ([]byte, []int) {
	return file_msggateway_proto_rawDescGZIP(), []int{10}
}

func (x *FailedDetail) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SingleDetail struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status              int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	SinglePlatformToken []*SinglePlatformToken `protobuf:"bytes,3,rep,name=single_platform_token,json=singlePlatformToken,proto3" json:"single_platform_token,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SingleDetail) Reset() {
	*x = SingleDetail{}
	mi := &file_msggateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleDetail) ProtoMessage() {}

func (x *SingleDetail) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleDetail.ProtoReflect.Descriptor instead.
func (*SingleDetail) Descriptor() ([]byte, []int) {
	return file_msggateway_proto_rawDescGZIP(), []int{11}
}

func (x *SingleDetail) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SingleDetail) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SingleDetail) GetSinglePlatformToken() []*SinglePlatformToken {
	if x != nil {
		return x.SinglePlatformToken
	}
	return nil
}

type SinglePlatformToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlatformId    int32                  `protobuf:"varint,1,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Token         []string               `protobuf:"bytes,3,rep,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SinglePlatformToken) Reset() {
	*x = SinglePlatformToken{}
	mi := &file_msggateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SinglePlatformToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinglePlatformToken) ProtoMessage() {}

func (x *SinglePlatformToken) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinglePlatformToken.ProtoReflect.Descriptor instead.
func (*SinglePlatformToken) Descriptor() ([]byte, []int) {
	return file_msggateway_proto_rawDescGZIP(), []int{12}
}

func (x *SinglePlatformToken) GetPlatformId() int32 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *SinglePlatformToken) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SinglePlatformToken) GetToken() []string {
	if x != nil {
		return x.Token
	}
	return nil
}

type KickUserOfflineReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlatformId     int32                  `protobuf:"varint,1,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	KickUserIdList []string               `protobuf:"bytes,2,rep,name=kick_user_id_list,json=kickUserIdList,proto3" json:"kick_user_id_list,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KickUserOfflineReq) Reset() {
	*x = KickUserOfflineReq{}
	mi := &file_msggateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserOfflineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserOfflineReq) ProtoMessage() {}

func (x *KickUserOfflineReq) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserOfflineReq.ProtoReflect.Descriptor instead.
func (*KickUserOfflineReq) Descriptor() ([]byte, []int) {
	return file_msggateway_proto_rawDescGZIP(), []int{13}
}

func (x *KickUserOfflineReq) GetPlatformId() int32 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *KickUserOfflineReq) GetKickUserIdList() []string {
	if x != nil {
		return x.KickUserIdList
	}
	return nil
}

type KickUserOfflineResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickUserOfflineResp) Reset() {
	*x = KickUserOfflineResp{}
	mi := &file_msggateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserOfflineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserOfflineResp) ProtoMessage() {}

func (x *KickUserOfflineResp) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserOfflineResp.ProtoReflect.Descriptor instead.
func (*KickUserOfflineResp) Descriptor() ([]byte, []int) {
	return file_msggateway_proto_rawDescGZIP(), []int{14}
}

type MultiTerminalLoginCheckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlatformId    int32                  `protobuf:"varint,2,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiTerminalLoginCheckReq) Reset() {
	*x = MultiTerminalLoginCheckReq{}
	mi := &file_msggateway_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiTerminalLoginCheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiTerminalLoginCheckReq) ProtoMessage() {}

func (x *MultiTerminalLoginCheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiTerminalLoginCheckReq.ProtoReflect.Descriptor instead.
func (*MultiTerminalLoginCheckReq) Descriptor() ([]byte, []int) {
	return file_msggateway_proto_rawDescGZIP(), []int{15}
}

func (x *MultiTerminalLoginCheckReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MultiTerminalLoginCheckReq) GetPlatformId() int32 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *MultiTerminalLoginCheckReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type MultiTerminalLoginCheckResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiTerminalLoginCheckResp) Reset() {
	*x = MultiTerminalLoginCheckResp{}
	mi := &file_msggateway_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiTerminalLoginCheckResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiTerminalLoginCheckResp) ProtoMessage() {}

func (x *MultiTerminalLoginCheckResp) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiTerminalLoginCheckResp.ProtoReflect.Descriptor instead.
func (*MultiTerminalLoginCheckResp) Descriptor() ([]byte, []int) {
	return file_msggateway_proto_rawDescGZIP(), []int{16}
}

var File_msggateway_proto protoreflect.FileDescriptor

const file_msggateway_proto_rawDesc = "" +
	"\n" +
	"\x10msggateway.proto\x12\n" +
	"msggateway\x1a\x11sdkws/sdkws.proto\"d\n" +
	"\x10OnlinePushMsgReq\x12)\n" +
	"\bmsg_data\x18\x01 \x01(\v2\x0e.sdkws.MsgDataR\amsgData\x12%\n" +
	"\x0fpush_to_user_id\x18\x02 \x01(\tR\fpushToUserId\"L\n" +
	"\x11OnlinePushMsgResp\x127\n" +
	"\x04resp\x18\x01 \x03(\v2#.msggateway.SingleMsgToUserPlatformR\x04resp\"\x8b\x01\n" +
	"\x16SingleMsgToUserResults\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x127\n" +
	"\x04resp\x18\x02 \x03(\v2#.msggateway.SingleMsgToUserPlatformR\x04resp\x12\x1f\n" +
	"\vonline_push\x18\x03 \x01(\bR\n" +
	"onlinePush\"n\n" +
	"\x18OnlineBatchPushOneMsgReq\x12)\n" +
	"\bmsg_data\x18\x01 \x01(\v2\x0e.sdkws.MsgDataR\amsgData\x12'\n" +
	"\x10push_to_user_ids\x18\x02 \x03(\tR\rpushToUserIds\"m\n" +
	"\x19OnlineBatchPushOneMsgResp\x12P\n" +
	"\x12single_push_result\x18\x01 \x03(\v2\".msggateway.SingleMsgToUserResultsR\x10singlePushResult\"}\n" +
	"\x17SingleMsgToUserPlatform\x12\x1f\n" +
	"\vresult_code\x18\x01 \x01(\x03R\n" +
	"resultCode\x12\x17\n" +
	"\arecv_id\x18\x02 \x01(\tR\x06recvId\x12(\n" +
	"\x10recv_platform_id\x18\x03 \x01(\x05R\x0erecvPlatformId\"4\n" +
	"\x17GetUsersOnlineStatusReq\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"\x9b\x01\n" +
	"\x18GetUsersOnlineStatusResp\x12@\n" +
	"\x0esuccess_result\x18\x01 \x03(\v2\x19.msggateway.SuccessResultR\rsuccessResult\x12=\n" +
	"\rfailed_result\x18\x02 \x03(\v2\x18.msggateway.FailedDetailR\ffailedResult\"\x91\x01\n" +
	"\rSuccessResult\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12O\n" +
	"\x16detail_platform_status\x18\x03 \x03(\v2\x19.msggateway.SuccessDetailR\x14detailPlatformStatus\"\x84\x01\n" +
	"\rSuccessDetail\x12\x1f\n" +
	"\vplatform_id\x18\x01 \x01(\x05R\n" +
	"platformId\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\tR\x06connId\x12#\n" +
	"\ris_background\x18\x03 \x01(\bR\fisBackground\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"'\n" +
	"\fFailedDetail\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x94\x01\n" +
	"\fSingleDetail\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12S\n" +
	"\x15single_platform_token\x18\x03 \x03(\v2\x1f.msggateway.SinglePlatformTokenR\x13singlePlatformToken\"b\n" +
	"\x13SinglePlatformToken\x12\x1f\n" +
	"\vplatform_id\x18\x01 \x01(\x05R\n" +
	"platformId\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x14\n" +
	"\x05token\x18\x03 \x03(\tR\x05token\"`\n" +
	"\x12KickUserOfflineReq\x12\x1f\n" +
	"\vplatform_id\x18\x01 \x01(\x05R\n" +
	"platformId\x12)\n" +
	"\x11kick_user_id_list\x18\x02 \x03(\tR\x0ekickUserIdList\"\x15\n" +
	"\x13KickUserOfflineResp\"l\n" +
	"\x1aMultiTerminalLoginCheckReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vplatform_id\x18\x02 \x01(\x05R\n" +
	"platformId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"\x1d\n" +
	"\x1bMultiTerminalLoginCheckResp2\xd3\x04\n" +
	"\n" +
	"MsgGateway\x12L\n" +
	"\rOnlinePushMsg\x12\x1c.msggateway.OnlinePushMsgReq\x1a\x1d.msggateway.OnlinePushMsgResp\x12a\n" +
	"\x14GetUsersOnlineStatus\x12#.msggateway.GetUsersOnlineStatusReq\x1a$.msggateway.GetUsersOnlineStatusResp\x12d\n" +
	"\x15OnlineBatchPushOneMsg\x12$.msggateway.OnlineBatchPushOneMsgReq\x1a%.msggateway.OnlineBatchPushOneMsgResp\x12n\n" +
	"\x1fSuperGroupOnlineBatchPushOneMsg\x12$.msggateway.OnlineBatchPushOneMsgReq\x1a%.msggateway.OnlineBatchPushOneMsgResp\x12R\n" +
	"\x0fKickUserOffline\x12\x1e.msggateway.KickUserOfflineReq\x1a\x1f.msggateway.KickUserOfflineResp\x12j\n" +
	"\x17MultiTerminalLoginCheck\x12&.msggateway.MultiTerminalLoginCheckReq\x1a'.msggateway.MultiTerminalLoginCheckRespB\x19Z\x17SuIM/proto/msggatewaypbb\x06proto3"

var (
	file_msggateway_proto_rawDescOnce sync.Once
	file_msggateway_proto_rawDescData []byte
)

func file_msggateway_proto_rawDescGZIP() []byte {
	file_msggateway_proto_rawDescOnce.Do(func() {
		file_msggateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_msggateway_proto_rawDesc), len(file_msggateway_proto_rawDesc)))
	})
	return file_msggateway_proto_rawDescData
}

var file_msggateway_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_msggateway_proto_goTypes = []any{
	(*OnlinePushMsgReq)(nil),            // 0: msggateway.OnlinePushMsgReq
	(*OnlinePushMsgResp)(nil),           // 1: msggateway.OnlinePushMsgResp
	(*SingleMsgToUserResults)(nil),      // 2: msggateway.SingleMsgToUserResults
	(*OnlineBatchPushOneMsgReq)(nil),    // 3: msggateway.OnlineBatchPushOneMsgReq
	(*OnlineBatchPushOneMsgResp)(nil),   // 4: msggateway.OnlineBatchPushOneMsgResp
	(*SingleMsgToUserPlatform)(nil),     // 5: msggateway.SingleMsgToUserPlatform
	(*GetUsersOnlineStatusReq)(nil),     // 6: msggateway.GetUsersOnlineStatusReq
	(*GetUsersOnlineStatusResp)(nil),    // 7: msggateway.GetUsersOnlineStatusResp
	(*SuccessResult)(nil),               // 8: msggateway.SuccessResult
	(*SuccessDetail)(nil),               // 9: msggateway.SuccessDetail
	(*FailedDetail)(nil),                // 10: msggateway.FailedDetail
	(*SingleDetail)(nil),                // 11: msggateway.SingleDetail
	(*SinglePlatformToken)(nil),         // 12: msggateway.SinglePlatformToken
	(*KickUserOfflineReq)(nil),          // 13: msggateway.KickUserOfflineReq
	(*KickUserOfflineResp)(nil),         // 14: msggateway.KickUserOfflineResp
	(*MultiTerminalLoginCheckReq)(nil),  // 15: msggateway.MultiTerminalLoginCheckReq
	(*MultiTerminalLoginCheckResp)(nil), // 16: msggateway.MultiTerminalLoginCheckResp
	(*sdkws.MsgData)(nil),               // 17: sdkws.MsgData
}
var file_msggateway_proto_depIdxs = []int32{
	17, // 0: msggateway.OnlinePushMsgReq.msg_data:type_name -> sdkws.MsgData
	5,  // 1: msggateway.OnlinePushMsgResp.resp:type_name -> msggateway.SingleMsgToUserPlatform
	5,  // 2: msggateway.SingleMsgToUserResults.resp:type_name -> msggateway.SingleMsgToUserPlatform
	17, // 3: msggateway.OnlineBatchPushOneMsgReq.msg_data:type_name -> sdkws.MsgData
	2,  // 4: msggateway.OnlineBatchPushOneMsgResp.single_push_result:type_name -> msggateway.SingleMsgToUserResults
	8,  // 5: msggateway.GetUsersOnlineStatusResp.success_result:type_name -> msggateway.SuccessResult
	10, // 6: msggateway.GetUsersOnlineStatusResp.failed_result:type_name -> msggateway.FailedDetail
	9,  // 7: msggateway.SuccessResult.detail_platform_status:type_name -> msggateway.SuccessDetail
	12, // 8: msggateway.SingleDetail.single_platform_token:type_name -> msggateway.SinglePlatformToken
	0,  // 9: msggateway.MsgGateway.OnlinePushMsg:input_type -> msggateway.OnlinePushMsgReq
	6,  // 10: msggateway.MsgGateway.GetUsersOnlineStatus:input_type -> msggateway.GetUsersOnlineStatusReq
	3,  // 11: msggateway.MsgGateway.OnlineBatchPushOneMsg:input_type -> msggateway.OnlineBatchPushOneMsgReq
	3,  // 12: msggateway.MsgGateway.SuperGroupOnlineBatchPushOneMsg:input_type -> msggateway.OnlineBatchPushOneMsgReq
	13, // 13: msggateway.MsgGateway.KickUserOffline:input_type -> msggateway.KickUserOfflineReq
	15, // 14: msggateway.MsgGateway.MultiTerminalLoginCheck:input_type -> msggateway.MultiTerminalLoginCheckReq
	1,  // 15: msggateway.MsgGateway.OnlinePushMsg:output_type -> msggateway.OnlinePushMsgResp
	7,  // 16: msggateway.MsgGateway.GetUsersOnlineStatus:output_type -> msggateway.GetUsersOnlineStatusResp
	4,  // 17: msggateway.MsgGateway.OnlineBatchPushOneMsg:output_type -> msggateway.OnlineBatchPushOneMsgResp
	4,  // 18: msggateway.MsgGateway.SuperGroupOnlineBatchPushOneMsg:output_type -> msggateway.OnlineBatchPushOneMsgResp
	14, // 19: msggateway.MsgGateway.KickUserOffline:output_type -> msggateway.KickUserOfflineResp
	16, // 20: msggateway.MsgGateway.MultiTerminalLoginCheck:output_type -> msggateway.MultiTerminalLoginCheckResp
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_msggateway_proto_init() }
func file_msggateway_proto_init() {
	if File_msggateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msggateway_proto_rawDesc), len(file_msggateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_msggateway_proto_goTypes,
		DependencyIndexes: file_msggateway_proto_depIdxs,
		MessageInfos:      file_msggateway_proto_msgTypes,
	}.Build()
	File_msggateway_proto = out.File
	file_msggateway_proto_goTypes = nil
	file_msggateway_proto_depIdxs = nil
}
