syntax = "proto3";

package sdkws;

option go_package = "SuIM/proto/sdkws";

// MsgData 是跨服务共享的单条聊天消息轻量表示。
message MsgData {
  string client_msg_id = 1;
  string server_msg_id = 2;
  string conversation_id = 3;
  string send_id = 4;
  string recv_id = 5;
  string group_id = 6;
  int32  session_type = 7;
  int32  msg_from = 8;
  int32  content_type = 9;
  string content = 10;
  int64  seq = 11;
  int64  send_time = 12;
  int32  status = 13;
  string ex = 14;
  bool   is_read = 15;
  int32  sender_platform_id = 16;
  string sender_nickname = 17;
  string sender_face_url = 18;
  string options = 19;
  repeated string at_user_id_list = 20;
  string attached_info = 21;
}
