// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: rtc.proto

package rtcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CallId         string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	CallerId       string                 `protobuf:"bytes,3,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	CalleeId       string                 `protobuf:"bytes,4,opt,name=callee_id,json=calleeId,proto3" json:"callee_id,omitempty"`
	MediaType      string                 `protobuf:"bytes,5,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	EndReason      string                 `protobuf:"bytes,7,opt,name=end_reason,json=endReason,proto3" json:"end_reason,omitempty"`
	RoomName       string                 `protobuf:"bytes,8,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	StartedAt      int64                  `protobuf:"varint,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	AnsweredAt     int64                  `protobuf:"varint,10,opt,name=answered_at,json=answeredAt,proto3" json:"answered_at,omitempty"`
	EndedAt        int64                  `protobuf:"varint,11,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	DurationSec    int32                  `protobuf:"varint,12,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CallInfo) Reset() {
	*x = CallInfo{}
	mi := &file_rtc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallInfo) ProtoMessage() {}

func (x *CallInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallInfo.ProtoReflect.Descriptor instead.
func (*CallInfo) Descriptor() ([]byte, []int) {
	return file_rtc_proto_rawDescGZIP(), []int{0}
}

func (x *CallInfo) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *CallInfo) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *CallInfo) GetCallerId() string {
	if x != nil {
		return x.CallerId
	}
	return ""
}

func (x *CallInfo) GetCalleeId() string {
	if x != nil {
		return x.CalleeId
	}
	return ""
}

func (x *CallInfo) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *CallInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CallInfo) GetEndReason() string {
	if x != nil {
		return x.EndReason
	}
	return ""
}

func (x *CallInfo) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *CallInfo) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *CallInfo) GetAnsweredAt() int64 {
	if x != nil {
		return x.AnsweredAt
	}
	return 0
}

func (x *CallInfo) GetEndedAt() int64 {
	if x != nil {
		return x.EndedAt
	}
	return 0
}

func (x *CallInfo) GetDurationSec() int32 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

type InviteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallerId      string                 `protobuf:"bytes,1,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	CalleeId      string                 `protobuf:"bytes,2,opt,name=callee_id,json=calleeId,proto3" json:"callee_id,omitempty"`
	MediaType     string                 `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteReq) Reset() {
	*x = InviteReq{}
	mi := &file_rtc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteReq) ProtoMessage() {}

func (x *InviteReq) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteReq.ProtoReflect.Descriptor instead.
func (*InviteReq) Descriptor() ([]byte, []int) {
	return file_rtc_proto_rawDescGZIP(), []int{1}
}

func (x *InviteReq) GetCallerId() string {
	if x != nil {
		return x.CallerId
	}
	return ""
}

func (x *InviteReq) GetCalleeId() string {
	if x != nil {
		return x.CalleeId
	}
	return ""
}

func (x *InviteReq) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

type InviteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Call          *CallInfo              `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	LivekitUrl    string                 `protobuf:"bytes,3,opt,name=livekit_url,json=livekitUrl,proto3" json:"livekit_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteResp) Reset() {
	*x = InviteResp{}
	mi := &file_rtc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteResp) ProtoMessage() {}

func (x *InviteResp) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteResp.ProtoReflect.Descriptor instead.
func (*InviteResp) Descriptor() ([]byte, []int) {
	return file_rtc_proto_rawDescGZIP(), []int{2}
}

func (x *InviteResp) GetCall() *CallInfo {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *InviteResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *InviteResp) GetLivekitUrl() string {
	if x != nil {
		return x.LivekitUrl
	}
	return ""
}

type AcceptReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CallId        string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptReq) Reset() {
	*x = AcceptReq{}
	mi := &file_rtc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptReq) ProtoMessage() {}

func (x *AcceptReq) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptReq.ProtoReflect.Descriptor instead.
func (*AcceptReq) Descriptor() ([]byte, []int) {
	return file_rtc_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AcceptReq) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

type AcceptResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Call          *CallInfo              `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	LivekitUrl    string                 `protobuf:"bytes,3,opt,name=livekit_url,json=livekitUrl,proto3" json:"livekit_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptResp) Reset() {
	*x = AcceptResp{}
	mi := &file_rtc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptResp) ProtoMessage() {}

func (x *AcceptResp) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptResp.ProtoReflect.Descriptor instead.
func (*AcceptResp) Descriptor() ([]byte, []int) {
	return file_rtc_proto_rawDescGZIP(), []int{4}
}

func (x *AcceptResp) GetCall() *CallInfo {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *AcceptResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AcceptResp) GetLivekitUrl() string {
	if x != nil {
		return x.LivekitUrl
	}
	return ""
}

type RejectReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CallId        string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectReq) Reset() {
	*x = RejectReq{}
	mi := &file_rtc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectReq) ProtoMessage() {}

func (x *RejectReq) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectReq.ProtoReflect.Descriptor instead.
func (*RejectReq) Descriptor() ([]byte, []int) {
	return file_rtc_proto_rawDescGZIP(), []int{5}
}

func (x *RejectReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RejectReq) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

type RejectResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Call          *CallInfo              `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectResp) Reset() {
	*x = RejectResp{}
	mi := &file_rtc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectResp) ProtoMessage() {}

func (x *RejectResp) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectResp.ProtoReflect.Descriptor instead.
func (*RejectResp) Descriptor() ([]byte, []int) {
	return file_rtc_proto_rawDescGZIP(), []int{6}
}

func (x *RejectResp) GetCall() *CallInfo {
	if x != nil {
		return x.Call
	}
	return nil
}

type CancelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CallId        string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReq) Reset() {
	*x = CancelReq{}
	mi := &file_rtc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReq) ProtoMessage() {}

func (x *CancelReq) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReq.ProtoReflect.Descriptor instead.
func (*CancelReq) Descriptor() ([]byte, []int) {
	return file_rtc_proto_rawDescGZIP(), []int{7}
}

func (x *CancelReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CancelReq) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

type CancelResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Call          *CallInfo              `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResp) Reset() {
	*x = CancelResp{}
	mi := &file_rtc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResp) ProtoMessage() {}

func (x *CancelResp) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResp.ProtoReflect.Descriptor instead.
func (*CancelResp) Descriptor() ([]byte, []int) {
	return file_rtc_proto_rawDescGZIP(), []int{8}
}

func (x *CancelResp) GetCall() *CallInfo {
	if x != nil {
		return x.Call
	}
	return nil
}

type HangupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CallId        string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HangupReq) Reset() {
	*x = HangupReq{}
	mi := &file_rtc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HangupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HangupReq) ProtoMessage() {}

func (x *HangupReq) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HangupReq.ProtoReflect.Descriptor instead.
func (*HangupReq) Descriptor() ([]byte, []int) {
	return file_rtc_proto_rawDescGZIP(), []int{9}
}

func (x *HangupReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HangupReq) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

type HangupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Call          *CallInfo              `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HangupResp) Reset() {
	*x = HangupResp{}
	mi := &file_rtc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HangupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HangupResp) ProtoMessage() {}

func (x *HangupResp) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HangupResp.ProtoReflect.Descriptor instead.
func (*HangupResp) Descriptor() ([]byte, []int) {
	return file_rtc_proto_rawDescGZIP(), []int{10}
}

func (x *HangupResp) GetCall() *CallInfo {
	if x != nil {
		return x.Call
	}
	return nil
}

type GetCallReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CallId        string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallReq) Reset() {
	*x = GetCallReq{}
	mi := &file_rtc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallReq) ProtoMessage() {}

func (x *GetCallReq) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallReq.ProtoReflect.Descriptor instead.
func (*GetCallReq) Descriptor() ([]byte, []int) {
	return file_rtc_proto_rawDescGZIP(), []int{11}
}

func (x *GetCallReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetCallReq) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

type GetCallResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Call          *CallInfo              `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallResp) Reset() {
	*x = GetCallResp{}
	mi := &file_rtc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallResp) ProtoMessage() {}

func (x *GetCallResp) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallResp.ProtoReflect.Descriptor instead.
func (*GetCallResp) Descriptor() ([]byte, []int) {
	return file_rtc_proto_rawDescGZIP(), []int{12}
}

func (x *GetCallResp) GetCall() *CallInfo {
	if x != nil {
		return x.Call
	}
	return nil
}

type RefreshTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CallId        string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenReq) Reset() {
	*x = RefreshTokenReq{}
	mi := &file_rtc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenReq) ProtoMessage() {}

func (x *RefreshTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenReq.ProtoReflect.Descriptor instead.
func (*RefreshTokenReq) Descriptor() ([]byte, []int) {
	return file_rtc_proto_rawDescGZIP(), []int{13}
}

func (x *RefreshTokenReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RefreshTokenReq) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

type RefreshTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RoomName      string                 `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	LivekitUrl    string                 `protobuf:"bytes,3,opt,name=livekit_url,json=livekitUrl,proto3" json:"livekit_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResp) Reset() {
	*x = RefreshTokenResp{}
	mi := &file_rtc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResp) ProtoMessage() {}

func (x *RefreshTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_rtc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResp.ProtoReflect.Descriptor instead.
func (*RefreshTokenResp) Descriptor() ([]byte, []int) {
	return file_rtc_proto_rawDescGZIP(), []int{14}
}

func (x *RefreshTokenResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RefreshTokenResp) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *RefreshTokenResp) GetLivekitUrl() string {
	if x != nil {
		return x.LivekitUrl
	}
	return ""
}

var File_rtc_proto protoreflect.FileDescriptor

const file_rtc_proto_rawDesc = "" +
	"\n" +
	"\trtc.proto\x12\x03rtc\"\xf7\x02\n" +
	"\bCallInfo\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tcaller_id\x18\x03 \x01(\tR\bcallerId\x12\x1b\n" +
	"\tcallee_id\x18\x04 \x01(\tR\bcalleeId\x12\x1d\n" +
	"\n" +
	"media_type\x18\x05 \x01(\tR\tmediaType\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"end_reason\x18\a \x01(\tR\tendReason\x12\x1b\n" +
	"\troom_name\x18\b \x01(\tR\broomName\x12\x1d\n" +
	"\n" +
	"started_at\x18\t \x01(\x03R\tstartedAt\x12\x1f\n" +
	"\vanswered_at\x18\n" +
	" \x01(\x03R\n" +
	"answeredAt\x12\x19\n" +
	"\bended_at\x18\v \x01(\x03R\aendedAt\x12!\n" +
	"\fduration_sec\x18\f \x01(\x05R\vdurationSec\"d\n" +
	"\tInviteReq\x12\x1b\n" +
	"\tcaller_id\x18\x01 \x01(\tR\bcallerId\x12\x1b\n" +
	"\tcallee_id\x18\x02 \x01(\tR\bcalleeId\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\"f\n" +
	"\n" +
	"InviteResp\x12!\n" +
	"\x04call\x18\x01 \x01(\v2\r.rtc.CallInfoR\x04call\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1f\n" +
	"\vlivekit_url\x18\x03 \x01(\tR\n" +
	"livekitUrl\"=\n" +
	"\tAcceptReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\"f\n" +
	"\n" +
	"AcceptResp\x12!\n" +
	"\x04call\x18\x01 \x01(\v2\r.rtc.CallInfoR\x04call\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1f\n" +
	"\vlivekit_url\x18\x03 \x01(\tR\n" +
	"livekitUrl\"=\n" +
	"\tRejectReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\"/\n" +
	"\n" +
	"RejectResp\x12!\n" +
	"\x04call\x18\x01 \x01(\v2\r.rtc.CallInfoR\x04call\"=\n" +
	"\tCancelReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\"/\n" +
	"\n" +
	"CancelResp\x12!\n" +
	"\x04call\x18\x01 \x01(\v2\r.rtc.CallInfoR\x04call\"=\n" +
	"\tHangupReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\"/\n" +
	"\n" +
	"HangupResp\x12!\n" +
	"\x04call\x18\x01 \x01(\v2\r.rtc.CallInfoR\x04call\">\n" +
	"\n" +
	"GetCallReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\"0\n" +
	"\vGetCallResp\x12!\n" +
	"\x04call\x18\x01 \x01(\v2\r.rtc.CallInfoR\x04call\"C\n" +
	"\x0fRefreshTokenReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\"f\n" +
	"\x10RefreshTokenResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\troom_name\x18\x02 \x01(\tR\broomName\x12\x1f\n" +
	"\vlivekit_url\x18\x03 \x01(\tR\n" +
	"livekitUrl2\xce\x02\n" +
	"\n" +
	"RtcService\x12)\n" +
	"\x06Invite\x12\x0e.rtc.InviteReq\x1a\x0f.rtc.InviteResp\x12)\n" +
	"\x06Accept\x12\x0e.rtc.AcceptReq\x1a\x0f.rtc.AcceptResp\x12)\n" +
	"\x06Reject\x12\x0e.rtc.RejectReq\x1a\x0f.rtc.RejectResp\x12)\n" +
	"\x06Cancel\x12\x0e.rtc.CancelReq\x1a\x0f.rtc.CancelResp\x12)\n" +
	"\x06Hangup\x12\x0e.rtc.HangupReq\x1a\x0f.rtc.HangupResp\x12,\n" +
	"\aGetCall\x12\x0f.rtc.GetCallReq\x1a\x10.rtc.GetCallResp\x12;\n" +
	"\fRefreshToken\x12\x14.rtc.RefreshTokenReq\x1a\x15.rtc.RefreshTokenRespB\x12Z\x10SuIM/proto/rtcpbb\x06proto3"

var (
	file_rtc_proto_rawDescOnce sync.Once
	file_rtc_proto_rawDescData []byte
)

func file_rtc_proto_rawDescGZIP() []byte {
	file_rtc_proto_rawDescOnce.Do(func() {
		file_rtc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rtc_proto_rawDesc), len(file_rtc_proto_rawDesc)))
	})
	return file_rtc_proto_rawDescData
}

var file_rtc_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_rtc_proto_goTypes = []any{
	(*CallInfo)(nil),         // 0: rtc.CallInfo
	(*InviteReq)(nil),        // 1: rtc.InviteReq
	(*InviteResp)(nil),       // 2: rtc.InviteResp
	(*AcceptReq)(nil),        // 3: rtc.AcceptReq
	(*AcceptResp)(nil),       // 4: rtc.AcceptResp
	(*RejectReq)(nil),        // 5: rtc.RejectReq
	(*RejectResp)(nil),       // 6: rtc.RejectResp
	(*CancelReq)(nil),        // 7: rtc.CancelReq
	(*CancelResp)(nil),       // 8: rtc.CancelResp
	(*HangupReq)(nil),        // 9: rtc.HangupReq
	(*HangupResp)(nil),       // 10: rtc.HangupResp
	(*GetCallReq)(nil),       // 11: rtc.GetCallReq
	(*GetCallResp)(nil),      // 12: rtc.GetCallResp
	(*RefreshTokenReq)(nil),  // 13: rtc.RefreshTokenReq
	(*RefreshTokenResp)(nil), // 14: rtc.RefreshTokenResp
}
var file_rtc_proto_depIdxs = []int32{
	0,  // 0: rtc.InviteResp.call:type_name -> rtc.CallInfo
	0,  // 1: rtc.AcceptResp.call:type_name -> rtc.CallInfo
	0,  // 2: rtc.RejectResp.call:type_name -> rtc.CallInfo
	0,  // 3: rtc.CancelResp.call:type_name -> rtc.CallInfo
	0,  // 4: rtc.HangupResp.call:type_name -> rtc.CallInfo
	0,  // 5: rtc.GetCallResp.call:type_name -> rtc.CallInfo
	1,  // 6: rtc.RtcService.Invite:input_type -> rtc.InviteReq
	3,  // 7: rtc.RtcService.Accept:input_type -> rtc.AcceptReq
	5,  // 8: rtc.RtcService.Reject:input_type -> rtc.RejectReq
	7,  // 9: rtc.RtcService.Cancel:input_type -> rtc.CancelReq
	9,  // 10: rtc.RtcService.Hangup:input_type -> rtc.HangupReq
	11, // 11: rtc.RtcService.GetCall:input_type -> rtc.GetCallReq
	13, // 12: rtc.RtcService.RefreshToken:input_type -> rtc.RefreshTokenReq
	2,  // 13: rtc.RtcService.Invite:output_type -> rtc.InviteResp
	4,  // 14: rtc.RtcService.Accept:output_type -> rtc.AcceptResp
	6,  // 15: rtc.RtcService.Reject:output_type -> rtc.RejectResp
	8,  // 16: rtc.RtcService.Cancel:output_type -> rtc.CancelResp
	10, // 17: rtc.RtcService.Hangup:output_type -> rtc.HangupResp
	12, // 18: rtc.RtcService.GetCall:output_type -> rtc.GetCallResp
	14, // 19: rtc.RtcService.RefreshToken:output_type -> rtc.RefreshTokenResp
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_rtc_proto_init() }
func file_rtc_proto_init() {
	if File_rtc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rtc_proto_rawDesc), len(file_rtc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rtc_proto_goTypes,
		DependencyIndexes: file_rtc_proto_depIdxs,
		MessageInfos:      file_rtc_proto_msgTypes,
	}.Build()
	File_rtc_proto = out.File
	file_rtc_proto_goTypes = nil
	file_rtc_proto_depIdxs = nil
}
