// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.2
// source: rtc.proto

package rtcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RtcService_Invite_FullMethodName       = "/rtc.RtcService/Invite"
	RtcService_Accept_FullMethodName       = "/rtc.RtcService/Accept"
	RtcService_Reject_FullMethodName       = "/rtc.RtcService/Reject"
	RtcService_Cancel_FullMethodName       = "/rtc.RtcService/Cancel"
	RtcService_Hangup_FullMethodName       = "/rtc.RtcService/Hangup"
	RtcService_GetCall_FullMethodName      = "/rtc.RtcService/GetCall"
	RtcService_RefreshToken_FullMethodName = "/rtc.RtcService/RefreshToken"
)

// RtcServiceClient is the client API for RtcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RtcServiceClient interface {
	Invite(ctx context.Context, in *InviteReq, opts ...grpc.CallOption) (*InviteResp, error)
	Accept(ctx context.Context, in *AcceptReq, opts ...grpc.CallOption) (*AcceptResp, error)
	Reject(ctx context.Context, in *RejectReq, opts ...grpc.CallOption) (*RejectResp, error)
	Cancel(ctx context.Context, in *CancelReq, opts ...grpc.CallOption) (*CancelResp, error)
	Hangup(ctx context.Context, in *HangupReq, opts ...grpc.CallOption) (*HangupResp, error)
	GetCall(ctx context.Context, in *GetCallReq, opts ...grpc.CallOption) (*GetCallResp, error)
	RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error)
}

type rtcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRtcServiceClient(cc grpc.ClientConnInterface) RtcServiceClient {
	return &rtcServiceClient{cc}
}

func (c *rtcServiceClient) Invite(ctx context.Context, in *InviteReq, opts ...grpc.CallOption) (*InviteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InviteResp)
	err := c.cc.Invoke(ctx, RtcService_Invite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtcServiceClient) Accept(ctx context.Context, in *AcceptReq, opts ...grpc.CallOption) (*AcceptResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptResp)
	err := c.cc.Invoke(ctx, RtcService_Accept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtcServiceClient) Reject(ctx context.Context, in *RejectReq, opts ...grpc.CallOption) (*RejectResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectResp)
	err := c.cc.Invoke(ctx, RtcService_Reject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtcServiceClient) Cancel(ctx context.Context, in *CancelReq, opts ...grpc.CallOption) (*CancelResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResp)
	err := c.cc.Invoke(ctx, RtcService_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtcServiceClient) Hangup(ctx context.Context, in *HangupReq, opts ...grpc.CallOption) (*HangupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HangupResp)
	err := c.cc.Invoke(ctx, RtcService_Hangup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtcServiceClient) GetCall(ctx context.Context, in *GetCallReq, opts ...grpc.CallOption) (*GetCallResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCallResp)
	err := c.cc.Invoke(ctx, RtcService_GetCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rtcServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResp)
	err := c.cc.Invoke(ctx, RtcService_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RtcServiceServer is the server API for RtcService service.
// All implementations must embed UnimplementedRtcServiceServer
// for forward compatibility.
type RtcServiceServer interface {
	Invite(context.Context, *InviteReq) (*InviteResp, error)
	Accept(context.Context, *AcceptReq) (*AcceptResp, error)
	Reject(context.Context, *RejectReq) (*RejectResp, error)
	Cancel(context.Context, *CancelReq) (*CancelResp, error)
	Hangup(context.Context, *HangupReq) (*HangupResp, error)
	GetCall(context.Context, *GetCallReq) (*GetCallResp, error)
	RefreshToken(context.Context, *RefreshTokenReq) (*RefreshTokenResp, error)
	mustEmbedUnimplementedRtcServiceServer()
}

// UnimplementedRtcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRtcServiceServer struct{}

func (UnimplementedRtcServiceServer) Invite(context.Context, *InviteReq) (*InviteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Invite not implemented")
}
func (UnimplementedRtcServiceServer) Accept(context.Context, *AcceptReq) (*AcceptResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Accept not implemented")
}
func (UnimplementedRtcServiceServer) Reject(context.Context, *RejectReq) (*RejectResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Reject not implemented")
}
func (UnimplementedRtcServiceServer) Cancel(context.Context, *CancelReq) (*CancelResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedRtcServiceServer) Hangup(context.Context, *HangupReq) (*HangupResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Hangup not implemented")
}
func (UnimplementedRtcServiceServer) GetCall(context.Context, *GetCallReq) (*GetCallResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCall not implemented")
}
func (UnimplementedRtcServiceServer) RefreshToken(context.Context, *RefreshTokenReq) (*RefreshTokenResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedRtcServiceServer) mustEmbedUnimplementedRtcServiceServer() {}
func (UnimplementedRtcServiceServer) testEmbeddedByValue()                    {}

// UnsafeRtcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RtcServiceServer will
// result in compilation errors.
type UnsafeRtcServiceServer interface {
	mustEmbedUnimplementedRtcServiceServer()
}

func RegisterRtcServiceServer(s grpc.ServiceRegistrar, srv RtcServiceServer) {
	// If the following call panics, it indicates UnimplementedRtcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RtcService_ServiceDesc, srv)
}

func _RtcService_Invite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtcServiceServer).Invite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RtcService_Invite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtcServiceServer).Invite(ctx, req.(*InviteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RtcService_Accept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtcServiceServer).Accept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RtcService_Accept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtcServiceServer).Accept(ctx, req.(*AcceptReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RtcService_Reject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtcServiceServer).Reject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RtcService_Reject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtcServiceServer).Reject(ctx, req.(*RejectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RtcService_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtcServiceServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RtcService_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtcServiceServer).Cancel(ctx, req.(*CancelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RtcService_Hangup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HangupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtcServiceServer).Hangup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RtcService_Hangup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtcServiceServer).Hangup(ctx, req.(*HangupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RtcService_GetCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCallReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtcServiceServer).GetCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RtcService_GetCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtcServiceServer).GetCall(ctx, req.(*GetCallReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RtcService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RtcServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RtcService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RtcServiceServer).RefreshToken(ctx, req.(*RefreshTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RtcService_ServiceDesc is the grpc.ServiceDesc for RtcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RtcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rtc.RtcService",
	HandlerType: (*RtcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invite",
			Handler:    _RtcService_Invite_Handler,
		},
		{
			MethodName: "Accept",
			Handler:    _RtcService_Accept_Handler,
		},
		{
			MethodName: "Reject",
			Handler:    _RtcService_Reject_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _RtcService_Cancel_Handler,
		},
		{
			MethodName: "Hangup",
			Handler:    _RtcService_Hangup_Handler,
		},
		{
			MethodName: "GetCall",
			Handler:    _RtcService_GetCall_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _RtcService_RefreshToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rtc.proto",
}
