// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/file.proto

package filepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        string                 `protobuf:"bytes,6,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Category      string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_proto_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_proto_file_proto_rawDescGZIP(), []int{0}
}

func (x *FileInfo) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileInfo) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *FileInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *FileInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FileInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FileInfo) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type InitiateUploadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        string                 `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateUploadReq) Reset() {
	*x = InitiateUploadReq{}
	mi := &file_proto_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateUploadReq) ProtoMessage() {}

func (x *InitiateUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateUploadReq.ProtoReflect.Descriptor instead.
func (*InitiateUploadReq) Descriptor() ([]byte, []int) {
	return file_proto_file_proto_rawDescGZIP(), []int{1}
}

func (x *InitiateUploadReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InitiateUploadReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InitiateUploadReq) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *InitiateUploadReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *InitiateUploadReq) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type InitiateUploadResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	File            *FileInfo              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	UploadUrl       string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	Headers         map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UploadExpiresAt int64                  `protobuf:"varint,4,opt,name=upload_expires_at,json=uploadExpiresAt,proto3" json:"upload_expires_at,omitempty"`
	AlreadyUploaded bool                   `protobuf:"varint,5,opt,name=already_uploaded,json=alreadyUploaded,proto3" json:"already_uploaded,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InitiateUploadResp) Reset() {
	*x = InitiateUploadResp{}
	mi := &file_proto_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateUploadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateUploadResp) ProtoMessage() {}

func (x *InitiateUploadResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateUploadResp.ProtoReflect.Descriptor instead.
func (*InitiateUploadResp) Descriptor() ([]byte, []int) {
	return file_proto_file_proto_rawDescGZIP(), []int{2}
}

func (x *InitiateUploadResp) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *InitiateUploadResp) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *InitiateUploadResp) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *InitiateUploadResp) GetUploadExpiresAt() int64 {
	if x != nil {
		return x.UploadExpiresAt
	}
	return 0
}

func (x *InitiateUploadResp) GetAlreadyUploaded() bool {
	if x != nil {
		return x.AlreadyUploaded
	}
	return false
}

type CompleteUploadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteUploadReq) Reset() {
	*x = CompleteUploadReq{}
	mi := &file_proto_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadReq) ProtoMessage() {}

func (x *CompleteUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadReq.ProtoReflect.Descriptor instead.
func (*CompleteUploadReq) Descriptor() ([]byte, []int) {
	return file_proto_file_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteUploadReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CompleteUploadReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type CompleteUploadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileInfo              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteUploadResp) Reset() {
	*x = CompleteUploadResp{}
	mi := &file_proto_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadResp) ProtoMessage() {}

func (x *CompleteUploadResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadResp.ProtoReflect.Descriptor instead.
func (*CompleteUploadResp) Descriptor() ([]byte, []int) {
	return file_proto_file_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteUploadResp) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

type BindFileReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileId         string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BindFileReq) Reset() {
	*x = BindFileReq{}
	mi := &file_proto_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindFileReq) ProtoMessage() {}

func (x *BindFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindFileReq.ProtoReflect.Descriptor instead.
func (*BindFileReq) Descriptor() ([]byte, []int) {
	return file_proto_file_proto_rawDescGZIP(), []int{5}
}

func (x *BindFileReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BindFileReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *BindFileReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type BindFileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileInfo              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindFileResp) Reset() {
	*x = BindFileResp{}
	mi := &file_proto_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindFileResp) ProtoMessage() {}

func (x *BindFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindFileResp.ProtoReflect.Descriptor instead.
func (*BindFileResp) Descriptor() ([]byte, []int) {
	return file_proto_file_proto_rawDescGZIP(), []int{6}
}

func (x *BindFileResp) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

type GetDownloadURLReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadURLReq) Reset() {
	*x = GetDownloadURLReq{}
	mi := &file_proto_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadURLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadURLReq) ProtoMessage() {}

func (x *GetDownloadURLReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadURLReq.ProtoReflect.Descriptor instead.
func (*GetDownloadURLReq) Descriptor() ([]byte, []int) {
	return file_proto_file_proto_rawDescGZIP(), []int{7}
}

func (x *GetDownloadURLReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetDownloadURLReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type GetDownloadURLResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileInfo              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,2,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadURLResp) Reset() {
	*x = GetDownloadURLResp{}
	mi := &file_proto_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadURLResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadURLResp) ProtoMessage() {}

func (x *GetDownloadURLResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadURLResp.ProtoReflect.Descriptor instead.
func (*GetDownloadURLResp) Descriptor() ([]byte, []int) {
	return file_proto_file_proto_rawDescGZIP(), []int{8}
}

func (x *GetDownloadURLResp) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *GetDownloadURLResp) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *GetDownloadURLResp) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type GetFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileReq) Reset() {
	*x = GetFileReq{}
	mi := &file_proto_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileReq) ProtoMessage() {}

func (x *GetFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileReq.ProtoReflect.Descriptor instead.
func (*GetFileReq) Descriptor() ([]byte, []int) {
	return file_proto_file_proto_rawDescGZIP(), []int{9}
}

func (x *GetFileReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFileReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type GetFileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileInfo              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileResp) Reset() {
	*x = GetFileResp{}
	mi := &file_proto_file_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResp) ProtoMessage() {}

func (x *GetFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResp.ProtoReflect.Descriptor instead.
func (*GetFileResp) Descriptor() ([]byte, []int) {
	return file_proto_file_proto_rawDescGZIP(), []int{10}
}

func (x *GetFileResp) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

type DeleteFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileReq) Reset() {
	*x = DeleteFileReq{}
	mi := &file_proto_file_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileReq) ProtoMessage() {}

func (x *DeleteFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileReq.ProtoReflect.Descriptor instead.
func (*DeleteFileReq) Descriptor() ([]byte, []int) {
	return file_proto_file_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteFileReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteFileReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type DeleteFileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResp) Reset() {
	*x = DeleteFileResp{}
	mi := &file_proto_file_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResp) ProtoMessage() {}

func (x *DeleteFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResp.ProtoReflect.Descriptor instead.
func (*DeleteFileResp) Descriptor() ([]byte, []int) {
	return file_proto_file_proto_rawDescGZIP(), []int{12}
}

var File_proto_file_proto protoreflect.FileDescriptor

const file_proto_file_proto_rawDesc = "" +
	"\n" +
	"\x10proto/file.proto\x12\x04file\"\x93\x02\n" +
	"\bFileInfo\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\x06 \x01(\tR\x06sha256\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\x03R\texpiresAt\"\x8f\x01\n" +
	"\x11InitiateUploadReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\x05 \x01(\tR\x06sha256\"\xab\x02\n" +
	"\x12InitiateUploadResp\x12\"\n" +
	"\x04file\x18\x01 \x01(\v2\x0e.file.FileInfoR\x04file\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x12?\n" +
	"\aheaders\x18\x03 \x03(\v2%.file.InitiateUploadResp.HeadersEntryR\aheaders\x12*\n" +
	"\x11upload_expires_at\x18\x04 \x01(\x03R\x0fuploadExpiresAt\x12)\n" +
	"\x10already_uploaded\x18\x05 \x01(\bR\x0falreadyUploaded\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\x11CompleteUploadReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\"8\n" +
	"\x12CompleteUploadResp\x12\"\n" +
	"\x04file\x18\x01 \x01(\v2\x0e.file.FileInfoR\x04file\"h\n" +
	"\vBindFileReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\"2\n" +
	"\fBindFileResp\x12\"\n" +
	"\x04file\x18\x01 \x01(\v2\x0e.file.FileInfoR\x04file\"E\n" +
	"\x11GetDownloadURLReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\"z\n" +
	"\x12GetDownloadURLResp\x12\"\n" +
	"\x04file\x18\x01 \x01(\v2\x0e.file.FileInfoR\x04file\x12!\n" +
	"\fdownload_url\x18\x02 \x01(\tR\vdownloadUrl\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\">\n" +
	"\n" +
	"GetFileReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\"1\n" +
	"\vGetFileResp\x12\"\n" +
	"\x04file\x18\x01 \x01(\v2\x0e.file.FileInfoR\x04file\"A\n" +
	"\rDeleteFileReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\"\x10\n" +
	"\x0eDeleteFileResp2\xf8\x02\n" +
	"\vFileService\x12C\n" +
	"\x0eInitiateUpload\x12\x17.file.InitiateUploadReq\x1a\x18.file.InitiateUploadResp\x12C\n" +
	"\x0eCompleteUpload\x12\x17.file.CompleteUploadReq\x1a\x18.file.CompleteUploadResp\x121\n" +
	"\bBindFile\x12\x11.file.BindFileReq\x1a\x12.file.BindFileResp\x12C\n" +
	"\x0eGetDownloadURL\x12\x17.file.GetDownloadURLReq\x1a\x18.file.GetDownloadURLResp\x12.\n" +
	"\aGetFile\x12\x10.file.GetFileReq\x1a\x11.file.GetFileResp\x127\n" +
	"\n" +
	"DeleteFile\x12\x13.file.DeleteFileReq\x1a\x14.file.DeleteFileRespB\x13Z\x11SuIM/proto/filepbb\x06proto3"

var (
	file_proto_file_proto_rawDescOnce sync.Once
	file_proto_file_proto_rawDescData []byte
)

func file_proto_file_proto_rawDescGZIP() []byte {
	file_proto_file_proto_rawDescOnce.Do(func() {
		file_proto_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_file_proto_rawDesc), len(file_proto_file_proto_rawDesc)))
	})
	return file_proto_file_proto_rawDescData
}

var file_proto_file_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_file_proto_goTypes = []any{
	(*FileInfo)(nil),           // 0: file.FileInfo
	(*InitiateUploadReq)(nil),  // 1: file.InitiateUploadReq
	(*InitiateUploadResp)(nil), // 2: file.InitiateUploadResp
	(*CompleteUploadReq)(nil),  // 3: file.CompleteUploadReq
	(*CompleteUploadResp)(nil), // 4: file.CompleteUploadResp
	(*BindFileReq)(nil),        // 5: file.BindFileReq
	(*BindFileResp)(nil),       // 6: file.BindFileResp
	(*GetDownloadURLReq)(nil),  // 7: file.GetDownloadURLReq
	(*GetDownloadURLResp)(nil), // 8: file.GetDownloadURLResp
	(*GetFileReq)(nil),         // 9: file.GetFileReq
	(*GetFileResp)(nil),        // 10: file.GetFileResp
	(*DeleteFileReq)(nil),      // 11: file.DeleteFileReq
	(*DeleteFileResp)(nil),     // 12: file.DeleteFileResp
	nil,                        // 13: file.InitiateUploadResp.HeadersEntry
}
var file_proto_file_proto_depIdxs = []int32{
	0,  // 0: file.InitiateUploadResp.file:type_name -> file.FileInfo
	13, // 1: file.InitiateUploadResp.headers:type_name -> file.InitiateUploadResp.HeadersEntry
	0,  // 2: file.CompleteUploadResp.file:type_name -> file.FileInfo
	0,  // 3: file.BindFileResp.file:type_name -> file.FileInfo
	0,  // 4: file.GetDownloadURLResp.file:type_name -> file.FileInfo
	0,  // 5: file.GetFileResp.file:type_name -> file.FileInfo
	1,  // 6: file.FileService.InitiateUpload:input_type -> file.InitiateUploadReq
	3,  // 7: file.FileService.CompleteUpload:input_type -> file.CompleteUploadReq
	5,  // 8: file.FileService.BindFile:input_type -> file.BindFileReq
	7,  // 9: file.FileService.GetDownloadURL:input_type -> file.GetDownloadURLReq
	9,  // 10: file.FileService.GetFile:input_type -> file.GetFileReq
	11, // 11: file.FileService.DeleteFile:input_type -> file.DeleteFileReq
	2,  // 12: file.FileService.InitiateUpload:output_type -> file.InitiateUploadResp
	4,  // 13: file.FileService.CompleteUpload:output_type -> file.CompleteUploadResp
	6,  // 14: file.FileService.BindFile:output_type -> file.BindFileResp
	8,  // 15: file.FileService.GetDownloadURL:output_type -> file.GetDownloadURLResp
	10, // 16: file.FileService.GetFile:output_type -> file.GetFileResp
	12, // 17: file.FileService.DeleteFile:output_type -> file.DeleteFileResp
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_file_proto_init() }
func file_proto_file_proto_init() {
	if File_proto_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_file_proto_rawDesc), len(file_proto_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_file_proto_goTypes,
		DependencyIndexes: file_proto_file_proto_depIdxs,
		MessageInfos:      file_proto_file_proto_msgTypes,
	}.Build()
	File_proto_file_proto = out.File
	file_proto_file_proto_goTypes = nil
	file_proto_file_proto_depIdxs = nil
}
