// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: relation.proto

package relationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --------------- FriendRequestInfo ---------------
// status: 0 = pending, 1 = accepted, -1 = rejected
type FriendRequestInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    string                 `protobuf:"bytes,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      string                 `protobuf:"bytes,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	HandleMsg     string                 `protobuf:"bytes,4,opt,name=handle_msg,json=handleMsg,proto3" json:"handle_msg,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequestInfo) Reset() {
	*x = FriendRequestInfo{}
	mi := &file_relation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestInfo) ProtoMessage() {}

func (x *FriendRequestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestInfo.ProtoReflect.Descriptor instead.
func (*FriendRequestInfo) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{0}
}

func (x *FriendRequestInfo) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *FriendRequestInfo) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *FriendRequestInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FriendRequestInfo) GetHandleMsg() string {
	if x != nil {
		return x.HandleMsg
	}
	return ""
}

func (x *FriendRequestInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FriendRequestInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FriendRequestInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// --------------- SendFriendRequest ---------------
type SendFriendRequestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    string                 `protobuf:"bytes,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      string                 `protobuf:"bytes,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestReq) Reset() {
	*x = SendFriendRequestReq{}
	mi := &file_relation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestReq) ProtoMessage() {}

func (x *SendFriendRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestReq.ProtoReflect.Descriptor instead.
func (*SendFriendRequestReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{1}
}

func (x *SendFriendRequestReq) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *SendFriendRequestReq) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *SendFriendRequestReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// empty: success is implied by gRPC status OK
type SendFriendRequestResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestResp) Reset() {
	*x = SendFriendRequestResp{}
	mi := &file_relation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestResp) ProtoMessage() {}

func (x *SendFriendRequestResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestResp.ProtoReflect.Descriptor instead.
func (*SendFriendRequestResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{2}
}

// --------------- RespondFriendApply ---------------
// Accept or reject a friend request. handle_result: 1 = accepted, -1 = rejected.
type RespondFriendApplyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    string                 `protobuf:"bytes,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`      // sender of the friend request
	ToUserId      string                 `protobuf:"bytes,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`            // receiver of the friend request (must equal the current user)
	HandleResult  int32                  `protobuf:"varint,3,opt,name=handle_result,json=handleResult,proto3" json:"handle_result,omitempty"` // 1 = accept, -1 = reject
	HandleMsg     string                 `protobuf:"bytes,4,opt,name=handle_msg,json=handleMsg,proto3" json:"handle_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondFriendApplyReq) Reset() {
	*x = RespondFriendApplyReq{}
	mi := &file_relation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondFriendApplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondFriendApplyReq) ProtoMessage() {}

func (x *RespondFriendApplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondFriendApplyReq.ProtoReflect.Descriptor instead.
func (*RespondFriendApplyReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{3}
}

func (x *RespondFriendApplyReq) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *RespondFriendApplyReq) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *RespondFriendApplyReq) GetHandleResult() int32 {
	if x != nil {
		return x.HandleResult
	}
	return 0
}

func (x *RespondFriendApplyReq) GetHandleMsg() string {
	if x != nil {
		return x.HandleMsg
	}
	return ""
}

type RespondFriendApplyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondFriendApplyResp) Reset() {
	*x = RespondFriendApplyResp{}
	mi := &file_relation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondFriendApplyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondFriendApplyResp) ProtoMessage() {}

func (x *RespondFriendApplyResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondFriendApplyResp.ProtoReflect.Descriptor instead.
func (*RespondFriendApplyResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{4}
}

// --------------- GetIncomingApplyTo ---------------
// Get received friend requests. handle_results filters by status; e.g. [0] = pending only.
type GetIncomingApplyToReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	HandleResults []int32                `protobuf:"varint,4,rep,packed,name=handle_results,json=handleResults,proto3" json:"handle_results,omitempty"` // 0=pending, 1=accepted, -1=rejected
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIncomingApplyToReq) Reset() {
	*x = GetIncomingApplyToReq{}
	mi := &file_relation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIncomingApplyToReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIncomingApplyToReq) ProtoMessage() {}

func (x *GetIncomingApplyToReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIncomingApplyToReq.ProtoReflect.Descriptor instead.
func (*GetIncomingApplyToReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{5}
}

func (x *GetIncomingApplyToReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetIncomingApplyToReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetIncomingApplyToReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetIncomingApplyToReq) GetHandleResults() []int32 {
	if x != nil {
		return x.HandleResults
	}
	return nil
}

type GetIncomingApplyToResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*FriendRequestInfo   `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIncomingApplyToResp) Reset() {
	*x = GetIncomingApplyToResp{}
	mi := &file_relation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIncomingApplyToResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIncomingApplyToResp) ProtoMessage() {}

func (x *GetIncomingApplyToResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIncomingApplyToResp.ProtoReflect.Descriptor instead.
func (*GetIncomingApplyToResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{6}
}

func (x *GetIncomingApplyToResp) GetRequests() []*FriendRequestInfo {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *GetIncomingApplyToResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// --------------- GetOutgoingApplyFrom ---------------
// Get sent friend requests. handle_results filters by status; e.g. [0] = pending only.
type GetOutgoingApplyFromReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	HandleResults []int32                `protobuf:"varint,4,rep,packed,name=handle_results,json=handleResults,proto3" json:"handle_results,omitempty"` // 0=pending, 1=accepted, -1=rejected
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOutgoingApplyFromReq) Reset() {
	*x = GetOutgoingApplyFromReq{}
	mi := &file_relation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOutgoingApplyFromReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOutgoingApplyFromReq) ProtoMessage() {}

func (x *GetOutgoingApplyFromReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOutgoingApplyFromReq.ProtoReflect.Descriptor instead.
func (*GetOutgoingApplyFromReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{7}
}

func (x *GetOutgoingApplyFromReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetOutgoingApplyFromReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetOutgoingApplyFromReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetOutgoingApplyFromReq) GetHandleResults() []int32 {
	if x != nil {
		return x.HandleResults
	}
	return nil
}

type GetOutgoingApplyFromResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*FriendRequestInfo   `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOutgoingApplyFromResp) Reset() {
	*x = GetOutgoingApplyFromResp{}
	mi := &file_relation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOutgoingApplyFromResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOutgoingApplyFromResp) ProtoMessage() {}

func (x *GetOutgoingApplyFromResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOutgoingApplyFromResp.ProtoReflect.Descriptor instead.
func (*GetOutgoingApplyFromResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{8}
}

func (x *GetOutgoingApplyFromResp) GetRequests() []*FriendRequestInfo {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *GetOutgoingApplyFromResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// --------------- GetUnhandledApplyCount ---------------
type GetUnhandledApplyCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnhandledApplyCountReq) Reset() {
	*x = GetUnhandledApplyCountReq{}
	mi := &file_relation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnhandledApplyCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnhandledApplyCountReq) ProtoMessage() {}

func (x *GetUnhandledApplyCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnhandledApplyCountReq.ProtoReflect.Descriptor instead.
func (*GetUnhandledApplyCountReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{9}
}

func (x *GetUnhandledApplyCountReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUnhandledApplyCountResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnhandledApplyCountResp) Reset() {
	*x = GetUnhandledApplyCountResp{}
	mi := &file_relation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnhandledApplyCountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnhandledApplyCountResp) ProtoMessage() {}

func (x *GetUnhandledApplyCountResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnhandledApplyCountResp.ProtoReflect.Descriptor instead.
func (*GetUnhandledApplyCountResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{10}
}

func (x *GetUnhandledApplyCountResp) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// --------------- DeleteFriend ---------------
type DeleteFriendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      string                 `protobuf:"bytes,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFriendReq) Reset() {
	*x = DeleteFriendReq{}
	mi := &file_relation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendReq) ProtoMessage() {}

func (x *DeleteFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendReq.ProtoReflect.Descriptor instead.
func (*DeleteFriendReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteFriendReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteFriendReq) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

type DeleteFriendResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFriendResp) Reset() {
	*x = DeleteFriendResp{}
	mi := &file_relation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFriendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendResp) ProtoMessage() {}

func (x *DeleteFriendResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendResp.ProtoReflect.Descriptor instead.
func (*DeleteFriendResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{12}
}

// --------------- FriendInfo ---------------
type FriendInfo struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	FriendUserId string                 `protobuf:"bytes,1,opt,name=friend_user_id,json=friendUserId,proto3" json:"friend_user_id,omitempty"`
	Remark       string                 `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	IsPinned     bool                   `protobuf:"varint,3,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"`
	CreateTime   int64                  `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // unix milliseconds
	// Display fields joined at read time (not stored on friend row).
	Nickname      string `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl     string `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendInfo) Reset() {
	*x = FriendInfo{}
	mi := &file_relation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendInfo) ProtoMessage() {}

func (x *FriendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendInfo.ProtoReflect.Descriptor instead.
func (*FriendInfo) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{13}
}

func (x *FriendInfo) GetFriendUserId() string {
	if x != nil {
		return x.FriendUserId
	}
	return ""
}

func (x *FriendInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *FriendInfo) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

func (x *FriendInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *FriendInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *FriendInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

// --------------- GetIncrementalFriends ---------------
type GetIncrementalFriendsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VersionId     string                 `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIncrementalFriendsReq) Reset() {
	*x = GetIncrementalFriendsReq{}
	mi := &file_relation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIncrementalFriendsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIncrementalFriendsReq) ProtoMessage() {}

func (x *GetIncrementalFriendsReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIncrementalFriendsReq.ProtoReflect.Descriptor instead.
func (*GetIncrementalFriendsReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{14}
}

func (x *GetIncrementalFriendsReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetIncrementalFriendsReq) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *GetIncrementalFriendsReq) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetIncrementalFriendsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	VersionId     string                 `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	Full          bool                   `protobuf:"varint,3,opt,name=full,proto3" json:"full,omitempty"`
	Delete        []string               `protobuf:"bytes,4,rep,name=delete,proto3" json:"delete,omitempty"`
	Insert        []*FriendInfo          `protobuf:"bytes,5,rep,name=insert,proto3" json:"insert,omitempty"`
	Update        []*FriendInfo          `protobuf:"bytes,6,rep,name=update,proto3" json:"update,omitempty"`
	SortVersion   uint64                 `protobuf:"varint,7,opt,name=sort_version,json=sortVersion,proto3" json:"sort_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIncrementalFriendsResp) Reset() {
	*x = GetIncrementalFriendsResp{}
	mi := &file_relation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIncrementalFriendsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIncrementalFriendsResp) ProtoMessage() {}

func (x *GetIncrementalFriendsResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIncrementalFriendsResp.ProtoReflect.Descriptor instead.
func (*GetIncrementalFriendsResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{15}
}

func (x *GetIncrementalFriendsResp) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetIncrementalFriendsResp) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *GetIncrementalFriendsResp) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

func (x *GetIncrementalFriendsResp) GetDelete() []string {
	if x != nil {
		return x.Delete
	}
	return nil
}

func (x *GetIncrementalFriendsResp) GetInsert() []*FriendInfo {
	if x != nil {
		return x.Insert
	}
	return nil
}

func (x *GetIncrementalFriendsResp) GetUpdate() []*FriendInfo {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *GetIncrementalFriendsResp) GetSortVersion() uint64 {
	if x != nil {
		return x.SortVersion
	}
	return 0
}

// --------------- GetFullFriendUserIDs ---------------
type GetFullFriendUserIDsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFullFriendUserIDsReq) Reset() {
	*x = GetFullFriendUserIDsReq{}
	mi := &file_relation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFullFriendUserIDsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFullFriendUserIDsReq) ProtoMessage() {}

func (x *GetFullFriendUserIDsReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFullFriendUserIDsReq.ProtoReflect.Descriptor instead.
func (*GetFullFriendUserIDsReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{16}
}

func (x *GetFullFriendUserIDsReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetFullFriendUserIDsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFullFriendUserIDsResp) Reset() {
	*x = GetFullFriendUserIDsResp{}
	mi := &file_relation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFullFriendUserIDsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFullFriendUserIDsResp) ProtoMessage() {}

func (x *GetFullFriendUserIDsResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFullFriendUserIDsResp.ProtoReflect.Descriptor instead.
func (*GetFullFriendUserIDsResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{17}
}

func (x *GetFullFriendUserIDsResp) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// --------------- NotificationUserInfoUpdate ---------------
type NotificationUserInfoUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // user whose nickname/avatar changed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationUserInfoUpdateReq) Reset() {
	*x = NotificationUserInfoUpdateReq{}
	mi := &file_relation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationUserInfoUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationUserInfoUpdateReq) ProtoMessage() {}

func (x *NotificationUserInfoUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationUserInfoUpdateReq.ProtoReflect.Descriptor instead.
func (*NotificationUserInfoUpdateReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{18}
}

func (x *NotificationUserInfoUpdateReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type NotificationUserInfoUpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationUserInfoUpdateResp) Reset() {
	*x = NotificationUserInfoUpdateResp{}
	mi := &file_relation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationUserInfoUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationUserInfoUpdateResp) ProtoMessage() {}

func (x *NotificationUserInfoUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationUserInfoUpdateResp.ProtoReflect.Descriptor instead.
func (*NotificationUserInfoUpdateResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{19}
}

// --------------- GetFriends ---------------
type GetFriendsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendsReq) Reset() {
	*x = GetFriendsReq{}
	mi := &file_relation_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendsReq) ProtoMessage() {}

func (x *GetFriendsReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendsReq.ProtoReflect.Descriptor instead.
func (*GetFriendsReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{20}
}

func (x *GetFriendsReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFriendsReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetFriendsReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetFriendsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friends       []*FriendInfo          `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendsResp) Reset() {
	*x = GetFriendsResp{}
	mi := &file_relation_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendsResp) ProtoMessage() {}

func (x *GetFriendsResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendsResp.ProtoReflect.Descriptor instead.
func (*GetFriendsResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{21}
}

func (x *GetFriendsResp) GetFriends() []*FriendInfo {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *GetFriendsResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// --------------- UpdateFriend ---------------
// Partial update: only set fields are applied. remark="" clears remark.
type UpdateFriendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerUserId   string                 `protobuf:"bytes,1,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	FriendUserId  string                 `protobuf:"bytes,2,opt,name=friend_user_id,json=friendUserId,proto3" json:"friend_user_id,omitempty"`
	Remark        *string                `protobuf:"bytes,3,opt,name=remark,proto3,oneof" json:"remark,omitempty"`
	IsPinned      *bool                  `protobuf:"varint,4,opt,name=is_pinned,json=isPinned,proto3,oneof" json:"is_pinned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFriendReq) Reset() {
	*x = UpdateFriendReq{}
	mi := &file_relation_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFriendReq) ProtoMessage() {}

func (x *UpdateFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFriendReq.ProtoReflect.Descriptor instead.
func (*UpdateFriendReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateFriendReq) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *UpdateFriendReq) GetFriendUserId() string {
	if x != nil {
		return x.FriendUserId
	}
	return ""
}

func (x *UpdateFriendReq) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

func (x *UpdateFriendReq) GetIsPinned() bool {
	if x != nil && x.IsPinned != nil {
		return *x.IsPinned
	}
	return false
}

type UpdateFriendResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFriendResp) Reset() {
	*x = UpdateFriendResp{}
	mi := &file_relation_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFriendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFriendResp) ProtoMessage() {}

func (x *UpdateFriendResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFriendResp.ProtoReflect.Descriptor instead.
func (*UpdateFriendResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{23}
}

// --------------- BlockUser ---------------
type BlockUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BlockedUserId string                 `protobuf:"bytes,2,opt,name=blocked_user_id,json=blockedUserId,proto3" json:"blocked_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockUserReq) Reset() {
	*x = BlockUserReq{}
	mi := &file_relation_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUserReq) ProtoMessage() {}

func (x *BlockUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUserReq.ProtoReflect.Descriptor instead.
func (*BlockUserReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{24}
}

func (x *BlockUserReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BlockUserReq) GetBlockedUserId() string {
	if x != nil {
		return x.BlockedUserId
	}
	return ""
}

type BlockUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockUserResp) Reset() {
	*x = BlockUserResp{}
	mi := &file_relation_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUserResp) ProtoMessage() {}

func (x *BlockUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUserResp.ProtoReflect.Descriptor instead.
func (*BlockUserResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{25}
}

// --------------- UnblockUser ---------------
type UnblockUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BlockedUserId string                 `protobuf:"bytes,2,opt,name=blocked_user_id,json=blockedUserId,proto3" json:"blocked_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockUserReq) Reset() {
	*x = UnblockUserReq{}
	mi := &file_relation_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockUserReq) ProtoMessage() {}

func (x *UnblockUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockUserReq.ProtoReflect.Descriptor instead.
func (*UnblockUserReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{26}
}

func (x *UnblockUserReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UnblockUserReq) GetBlockedUserId() string {
	if x != nil {
		return x.BlockedUserId
	}
	return ""
}

type UnblockUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockUserResp) Reset() {
	*x = UnblockUserResp{}
	mi := &file_relation_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockUserResp) ProtoMessage() {}

func (x *UnblockUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockUserResp.ProtoReflect.Descriptor instead.
func (*UnblockUserResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{27}
}

// --------------- BlackInfo ---------------
type BlackInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BlockedUserId  string                 `protobuf:"bytes,1,opt,name=blocked_user_id,json=blockedUserId,proto3" json:"blocked_user_id,omitempty"`
	CreateTime     int64                  `protobuf:"varint,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // unix milliseconds
	AddSource      int32                  `protobuf:"varint,3,opt,name=add_source,json=addSource,proto3" json:"add_source,omitempty"`
	OperatorUserId string                 `protobuf:"bytes,4,opt,name=operator_user_id,json=operatorUserId,proto3" json:"operator_user_id,omitempty"`
	Ex             string                 `protobuf:"bytes,5,opt,name=ex,proto3" json:"ex,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlackInfo) Reset() {
	*x = BlackInfo{}
	mi := &file_relation_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlackInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlackInfo) ProtoMessage() {}

func (x *BlackInfo) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlackInfo.ProtoReflect.Descriptor instead.
func (*BlackInfo) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{28}
}

func (x *BlackInfo) GetBlockedUserId() string {
	if x != nil {
		return x.BlockedUserId
	}
	return ""
}

func (x *BlackInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *BlackInfo) GetAddSource() int32 {
	if x != nil {
		return x.AddSource
	}
	return 0
}

func (x *BlackInfo) GetOperatorUserId() string {
	if x != nil {
		return x.OperatorUserId
	}
	return ""
}

func (x *BlackInfo) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

// --------------- GetBlockedUsers ---------------
type GetBlockedUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockedUsersReq) Reset() {
	*x = GetBlockedUsersReq{}
	mi := &file_relation_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockedUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockedUsersReq) ProtoMessage() {}

func (x *GetBlockedUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockedUsersReq.ProtoReflect.Descriptor instead.
func (*GetBlockedUsersReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{29}
}

func (x *GetBlockedUsersReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetBlockedUsersReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetBlockedUsersReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetBlockedUsersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blacks        []*BlackInfo           `protobuf:"bytes,1,rep,name=blacks,proto3" json:"blacks,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockedUsersResp) Reset() {
	*x = GetBlockedUsersResp{}
	mi := &file_relation_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockedUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockedUsersResp) ProtoMessage() {}

func (x *GetBlockedUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockedUsersResp.ProtoReflect.Descriptor instead.
func (*GetBlockedUsersResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{30}
}

func (x *GetBlockedUsersResp) GetBlacks() []*BlackInfo {
	if x != nil {
		return x.Blacks
	}
	return nil
}

func (x *GetBlockedUsersResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// --------------- IsFriend ---------------
// Both directions are queried independently; caller decides what "friend" means.
type IsFriendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User1         string                 `protobuf:"bytes,1,opt,name=user1,proto3" json:"user1,omitempty"`
	User2         string                 `protobuf:"bytes,2,opt,name=user2,proto3" json:"user2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFriendReq) Reset() {
	*x = IsFriendReq{}
	mi := &file_relation_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFriendReq) ProtoMessage() {}

func (x *IsFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFriendReq.ProtoReflect.Descriptor instead.
func (*IsFriendReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{31}
}

func (x *IsFriendReq) GetUser1() string {
	if x != nil {
		return x.User1
	}
	return ""
}

func (x *IsFriendReq) GetUser2() string {
	if x != nil {
		return x.User2
	}
	return ""
}

type IsFriendResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InUser1Friends bool                   `protobuf:"varint,1,opt,name=in_user1_friends,json=inUser1Friends,proto3" json:"in_user1_friends,omitempty"` // user2 is in user1's friend list
	InUser2Friends bool                   `protobuf:"varint,2,opt,name=in_user2_friends,json=inUser2Friends,proto3" json:"in_user2_friends,omitempty"` // user1 is in user2's friend list
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IsFriendResp) Reset() {
	*x = IsFriendResp{}
	mi := &file_relation_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFriendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFriendResp) ProtoMessage() {}

func (x *IsFriendResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFriendResp.ProtoReflect.Descriptor instead.
func (*IsFriendResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{32}
}

func (x *IsFriendResp) GetInUser1Friends() bool {
	if x != nil {
		return x.InUser1Friends
	}
	return false
}

func (x *IsFriendResp) GetInUser2Friends() bool {
	if x != nil {
		return x.InUser2Friends
	}
	return false
}

// --------------- IsBlack ---------------
type IsBlackReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User1         string                 `protobuf:"bytes,1,opt,name=user1,proto3" json:"user1,omitempty"`
	User2         string                 `protobuf:"bytes,2,opt,name=user2,proto3" json:"user2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsBlackReq) Reset() {
	*x = IsBlackReq{}
	mi := &file_relation_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsBlackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsBlackReq) ProtoMessage() {}

func (x *IsBlackReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsBlackReq.ProtoReflect.Descriptor instead.
func (*IsBlackReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{33}
}

func (x *IsBlackReq) GetUser1() string {
	if x != nil {
		return x.User1
	}
	return ""
}

func (x *IsBlackReq) GetUser2() string {
	if x != nil {
		return x.User2
	}
	return ""
}

type IsBlackResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InUser1Blacklist bool                   `protobuf:"varint,1,opt,name=in_user1_blacklist,json=inUser1Blacklist,proto3" json:"in_user1_blacklist,omitempty"` // user1 has blocked user2
	InUser2Blacklist bool                   `protobuf:"varint,2,opt,name=in_user2_blacklist,json=inUser2Blacklist,proto3" json:"in_user2_blacklist,omitempty"` // user2 has blocked user1
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IsBlackResp) Reset() {
	*x = IsBlackResp{}
	mi := &file_relation_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsBlackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsBlackResp) ProtoMessage() {}

func (x *IsBlackResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsBlackResp.ProtoReflect.Descriptor instead.
func (*IsBlackResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{34}
}

func (x *IsBlackResp) GetInUser1Blacklist() bool {
	if x != nil {
		return x.InUser1Blacklist
	}
	return false
}

func (x *IsBlackResp) GetInUser2Blacklist() bool {
	if x != nil {
		return x.InUser2Blacklist
	}
	return false
}

var File_relation_proto protoreflect.FileDescriptor

const file_relation_proto_rawDesc = "" +
	"\n" +
	"\x0erelation.proto\x12\brelation\"\xe2\x01\n" +
	"\x11FriendRequestInfo\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\tR\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\tR\btoUserId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"handle_msg\x18\x04 \x01(\tR\thandleMsg\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"p\n" +
	"\x14SendFriendRequestReq\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\tR\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\tR\btoUserId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x17\n" +
	"\x15SendFriendRequestResp\"\x9b\x01\n" +
	"\x15RespondFriendApplyReq\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\tR\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\tR\btoUserId\x12#\n" +
	"\rhandle_result\x18\x03 \x01(\x05R\fhandleResult\x12\x1d\n" +
	"\n" +
	"handle_msg\x18\x04 \x01(\tR\thandleMsg\"\x18\n" +
	"\x16RespondFriendApplyResp\"\x85\x01\n" +
	"\x15GetIncomingApplyToReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12%\n" +
	"\x0ehandle_results\x18\x04 \x03(\x05R\rhandleResults\"g\n" +
	"\x16GetIncomingApplyToResp\x127\n" +
	"\brequests\x18\x01 \x03(\v2\x1b.relation.FriendRequestInfoR\brequests\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x87\x01\n" +
	"\x17GetOutgoingApplyFromReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12%\n" +
	"\x0ehandle_results\x18\x04 \x03(\x05R\rhandleResults\"i\n" +
	"\x18GetOutgoingApplyFromResp\x127\n" +
	"\brequests\x18\x01 \x03(\v2\x1b.relation.FriendRequestInfoR\brequests\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"4\n" +
	"\x19GetUnhandledApplyCountReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"2\n" +
	"\x1aGetUnhandledApplyCountResp\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"G\n" +
	"\x0fDeleteFriendReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\tR\bfriendId\"\x12\n" +
	"\x10DeleteFriendResp\"\xc3\x01\n" +
	"\n" +
	"FriendInfo\x12$\n" +
	"\x0efriend_user_id\x18\x01 \x01(\tR\ffriendUserId\x12\x16\n" +
	"\x06remark\x18\x02 \x01(\tR\x06remark\x12\x1b\n" +
	"\tis_pinned\x18\x03 \x01(\bR\bisPinned\x12\x1f\n" +
	"\vcreate_time\x18\x04 \x01(\x03R\n" +
	"createTime\x12\x1a\n" +
	"\bnickname\x18\x05 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x06 \x01(\tR\tavatarUrl\"l\n" +
	"\x18GetIncrementalFriendsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\tR\tversionId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\"\xff\x01\n" +
	"\x19GetIncrementalFriendsResp\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\tR\tversionId\x12\x12\n" +
	"\x04full\x18\x03 \x01(\bR\x04full\x12\x16\n" +
	"\x06delete\x18\x04 \x03(\tR\x06delete\x12,\n" +
	"\x06insert\x18\x05 \x03(\v2\x14.relation.FriendInfoR\x06insert\x12,\n" +
	"\x06update\x18\x06 \x03(\v2\x14.relation.FriendInfoR\x06update\x12!\n" +
	"\fsort_version\x18\a \x01(\x04R\vsortVersion\"2\n" +
	"\x17GetFullFriendUserIDsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"5\n" +
	"\x18GetFullFriendUserIDsResp\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"8\n" +
	"\x1dNotificationUserInfoUpdateReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\" \n" +
	"\x1eNotificationUserInfoUpdateResp\"V\n" +
	"\rGetFriendsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"V\n" +
	"\x0eGetFriendsResp\x12.\n" +
	"\afriends\x18\x01 \x03(\v2\x14.relation.FriendInfoR\afriends\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xb3\x01\n" +
	"\x0fUpdateFriendReq\x12\"\n" +
	"\rowner_user_id\x18\x01 \x01(\tR\vownerUserId\x12$\n" +
	"\x0efriend_user_id\x18\x02 \x01(\tR\ffriendUserId\x12\x1b\n" +
	"\x06remark\x18\x03 \x01(\tH\x00R\x06remark\x88\x01\x01\x12 \n" +
	"\tis_pinned\x18\x04 \x01(\bH\x01R\bisPinned\x88\x01\x01B\t\n" +
	"\a_remarkB\f\n" +
	"\n" +
	"_is_pinned\"\x12\n" +
	"\x10UpdateFriendResp\"O\n" +
	"\fBlockUserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\x0fblocked_user_id\x18\x02 \x01(\tR\rblockedUserId\"\x0f\n" +
	"\rBlockUserResp\"Q\n" +
	"\x0eUnblockUserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\x0fblocked_user_id\x18\x02 \x01(\tR\rblockedUserId\"\x11\n" +
	"\x0fUnblockUserResp\"\xad\x01\n" +
	"\tBlackInfo\x12&\n" +
	"\x0fblocked_user_id\x18\x01 \x01(\tR\rblockedUserId\x12\x1f\n" +
	"\vcreate_time\x18\x02 \x01(\x03R\n" +
	"createTime\x12\x1d\n" +
	"\n" +
	"add_source\x18\x03 \x01(\x05R\taddSource\x12(\n" +
	"\x10operator_user_id\x18\x04 \x01(\tR\x0eoperatorUserId\x12\x0e\n" +
	"\x02ex\x18\x05 \x01(\tR\x02ex\"[\n" +
	"\x12GetBlockedUsersReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"X\n" +
	"\x13GetBlockedUsersResp\x12+\n" +
	"\x06blacks\x18\x01 \x03(\v2\x13.relation.BlackInfoR\x06blacks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"9\n" +
	"\vIsFriendReq\x12\x14\n" +
	"\x05user1\x18\x01 \x01(\tR\x05user1\x12\x14\n" +
	"\x05user2\x18\x02 \x01(\tR\x05user2\"b\n" +
	"\fIsFriendResp\x12(\n" +
	"\x10in_user1_friends\x18\x01 \x01(\bR\x0einUser1Friends\x12(\n" +
	"\x10in_user2_friends\x18\x02 \x01(\bR\x0einUser2Friends\"8\n" +
	"\n" +
	"IsBlackReq\x12\x14\n" +
	"\x05user1\x18\x01 \x01(\tR\x05user1\x12\x14\n" +
	"\x05user2\x18\x02 \x01(\tR\x05user2\"i\n" +
	"\vIsBlackResp\x12,\n" +
	"\x12in_user1_blacklist\x18\x01 \x01(\bR\x10inUser1Blacklist\x12,\n" +
	"\x12in_user2_blacklist\x18\x02 \x01(\bR\x10inUser2Blacklist2\xa3\n" +
	"\n" +
	"\x0fRelationService\x12T\n" +
	"\x11SendFriendRequest\x12\x1e.relation.SendFriendRequestReq\x1a\x1f.relation.SendFriendRequestResp\x12W\n" +
	"\x12RespondFriendApply\x12\x1f.relation.RespondFriendApplyReq\x1a .relation.RespondFriendApplyResp\x12W\n" +
	"\x12GetIncomingApplyTo\x12\x1f.relation.GetIncomingApplyToReq\x1a .relation.GetIncomingApplyToResp\x12]\n" +
	"\x14GetOutgoingApplyFrom\x12!.relation.GetOutgoingApplyFromReq\x1a\".relation.GetOutgoingApplyFromResp\x12c\n" +
	"\x16GetUnhandledApplyCount\x12#.relation.GetUnhandledApplyCountReq\x1a$.relation.GetUnhandledApplyCountResp\x12E\n" +
	"\fDeleteFriend\x12\x19.relation.DeleteFriendReq\x1a\x1a.relation.DeleteFriendResp\x12?\n" +
	"\n" +
	"GetFriends\x12\x17.relation.GetFriendsReq\x1a\x18.relation.GetFriendsResp\x12E\n" +
	"\fUpdateFriend\x12\x19.relation.UpdateFriendReq\x1a\x1a.relation.UpdateFriendResp\x12`\n" +
	"\x15GetIncrementalFriends\x12\".relation.GetIncrementalFriendsReq\x1a#.relation.GetIncrementalFriendsResp\x12]\n" +
	"\x14GetFullFriendUserIDs\x12!.relation.GetFullFriendUserIDsReq\x1a\".relation.GetFullFriendUserIDsResp\x12o\n" +
	"\x1aNotificationUserInfoUpdate\x12'.relation.NotificationUserInfoUpdateReq\x1a(.relation.NotificationUserInfoUpdateResp\x12<\n" +
	"\tBlockUser\x12\x16.relation.BlockUserReq\x1a\x17.relation.BlockUserResp\x12B\n" +
	"\vUnblockUser\x12\x18.relation.UnblockUserReq\x1a\x19.relation.UnblockUserResp\x12N\n" +
	"\x0fGetBlockedUsers\x12\x1c.relation.GetBlockedUsersReq\x1a\x1d.relation.GetBlockedUsersResp\x129\n" +
	"\bIsFriend\x12\x15.relation.IsFriendReq\x1a\x16.relation.IsFriendResp\x126\n" +
	"\aIsBlack\x12\x14.relation.IsBlackReq\x1a\x15.relation.IsBlackRespB\x17Z\x15SuIM/proto/relationpbb\x06proto3"

var (
	file_relation_proto_rawDescOnce sync.Once
	file_relation_proto_rawDescData []byte
)

func file_relation_proto_rawDescGZIP() []byte {
	file_relation_proto_rawDescOnce.Do(func() {
		file_relation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relation_proto_rawDesc), len(file_relation_proto_rawDesc)))
	})
	return file_relation_proto_rawDescData
}

var file_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_relation_proto_goTypes = []any{
	(*FriendRequestInfo)(nil),              // 0: relation.FriendRequestInfo
	(*SendFriendRequestReq)(nil),           // 1: relation.SendFriendRequestReq
	(*SendFriendRequestResp)(nil),          // 2: relation.SendFriendRequestResp
	(*RespondFriendApplyReq)(nil),          // 3: relation.RespondFriendApplyReq
	(*RespondFriendApplyResp)(nil),         // 4: relation.RespondFriendApplyResp
	(*GetIncomingApplyToReq)(nil),          // 5: relation.GetIncomingApplyToReq
	(*GetIncomingApplyToResp)(nil),         // 6: relation.GetIncomingApplyToResp
	(*GetOutgoingApplyFromReq)(nil),        // 7: relation.GetOutgoingApplyFromReq
	(*GetOutgoingApplyFromResp)(nil),       // 8: relation.GetOutgoingApplyFromResp
	(*GetUnhandledApplyCountReq)(nil),      // 9: relation.GetUnhandledApplyCountReq
	(*GetUnhandledApplyCountResp)(nil),     // 10: relation.GetUnhandledApplyCountResp
	(*DeleteFriendReq)(nil),                // 11: relation.DeleteFriendReq
	(*DeleteFriendResp)(nil),               // 12: relation.DeleteFriendResp
	(*FriendInfo)(nil),                     // 13: relation.FriendInfo
	(*GetIncrementalFriendsReq)(nil),       // 14: relation.GetIncrementalFriendsReq
	(*GetIncrementalFriendsResp)(nil),      // 15: relation.GetIncrementalFriendsResp
	(*GetFullFriendUserIDsReq)(nil),        // 16: relation.GetFullFriendUserIDsReq
	(*GetFullFriendUserIDsResp)(nil),       // 17: relation.GetFullFriendUserIDsResp
	(*NotificationUserInfoUpdateReq)(nil),  // 18: relation.NotificationUserInfoUpdateReq
	(*NotificationUserInfoUpdateResp)(nil), // 19: relation.NotificationUserInfoUpdateResp
	(*GetFriendsReq)(nil),                  // 20: relation.GetFriendsReq
	(*GetFriendsResp)(nil),                 // 21: relation.GetFriendsResp
	(*UpdateFriendReq)(nil),                // 22: relation.UpdateFriendReq
	(*UpdateFriendResp)(nil),               // 23: relation.UpdateFriendResp
	(*BlockUserReq)(nil),                   // 24: relation.BlockUserReq
	(*BlockUserResp)(nil),                  // 25: relation.BlockUserResp
	(*UnblockUserReq)(nil),                 // 26: relation.UnblockUserReq
	(*UnblockUserResp)(nil),                // 27: relation.UnblockUserResp
	(*BlackInfo)(nil),                      // 28: relation.BlackInfo
	(*GetBlockedUsersReq)(nil),             // 29: relation.GetBlockedUsersReq
	(*GetBlockedUsersResp)(nil),            // 30: relation.GetBlockedUsersResp
	(*IsFriendReq)(nil),                    // 31: relation.IsFriendReq
	(*IsFriendResp)(nil),                   // 32: relation.IsFriendResp
	(*IsBlackReq)(nil),                     // 33: relation.IsBlackReq
	(*IsBlackResp)(nil),                    // 34: relation.IsBlackResp
}
var file_relation_proto_depIdxs = []int32{
	0,  // 0: relation.GetIncomingApplyToResp.requests:type_name -> relation.FriendRequestInfo
	0,  // 1: relation.GetOutgoingApplyFromResp.requests:type_name -> relation.FriendRequestInfo
	13, // 2: relation.GetIncrementalFriendsResp.insert:type_name -> relation.FriendInfo
	13, // 3: relation.GetIncrementalFriendsResp.update:type_name -> relation.FriendInfo
	13, // 4: relation.GetFriendsResp.friends:type_name -> relation.FriendInfo
	28, // 5: relation.GetBlockedUsersResp.blacks:type_name -> relation.BlackInfo
	1,  // 6: relation.RelationService.SendFriendRequest:input_type -> relation.SendFriendRequestReq
	3,  // 7: relation.RelationService.RespondFriendApply:input_type -> relation.RespondFriendApplyReq
	5,  // 8: relation.RelationService.GetIncomingApplyTo:input_type -> relation.GetIncomingApplyToReq
	7,  // 9: relation.RelationService.GetOutgoingApplyFrom:input_type -> relation.GetOutgoingApplyFromReq
	9,  // 10: relation.RelationService.GetUnhandledApplyCount:input_type -> relation.GetUnhandledApplyCountReq
	11, // 11: relation.RelationService.DeleteFriend:input_type -> relation.DeleteFriendReq
	20, // 12: relation.RelationService.GetFriends:input_type -> relation.GetFriendsReq
	22, // 13: relation.RelationService.UpdateFriend:input_type -> relation.UpdateFriendReq
	14, // 14: relation.RelationService.GetIncrementalFriends:input_type -> relation.GetIncrementalFriendsReq
	16, // 15: relation.RelationService.GetFullFriendUserIDs:input_type -> relation.GetFullFriendUserIDsReq
	18, // 16: relation.RelationService.NotificationUserInfoUpdate:input_type -> relation.NotificationUserInfoUpdateReq
	24, // 17: relation.RelationService.BlockUser:input_type -> relation.BlockUserReq
	26, // 18: relation.RelationService.UnblockUser:input_type -> relation.UnblockUserReq
	29, // 19: relation.RelationService.GetBlockedUsers:input_type -> relation.GetBlockedUsersReq
	31, // 20: relation.RelationService.IsFriend:input_type -> relation.IsFriendReq
	33, // 21: relation.RelationService.IsBlack:input_type -> relation.IsBlackReq
	2,  // 22: relation.RelationService.SendFriendRequest:output_type -> relation.SendFriendRequestResp
	4,  // 23: relation.RelationService.RespondFriendApply:output_type -> relation.RespondFriendApplyResp
	6,  // 24: relation.RelationService.GetIncomingApplyTo:output_type -> relation.GetIncomingApplyToResp
	8,  // 25: relation.RelationService.GetOutgoingApplyFrom:output_type -> relation.GetOutgoingApplyFromResp
	10, // 26: relation.RelationService.GetUnhandledApplyCount:output_type -> relation.GetUnhandledApplyCountResp
	12, // 27: relation.RelationService.DeleteFriend:output_type -> relation.DeleteFriendResp
	21, // 28: relation.RelationService.GetFriends:output_type -> relation.GetFriendsResp
	23, // 29: relation.RelationService.UpdateFriend:output_type -> relation.UpdateFriendResp
	15, // 30: relation.RelationService.GetIncrementalFriends:output_type -> relation.GetIncrementalFriendsResp
	17, // 31: relation.RelationService.GetFullFriendUserIDs:output_type -> relation.GetFullFriendUserIDsResp
	19, // 32: relation.RelationService.NotificationUserInfoUpdate:output_type -> relation.NotificationUserInfoUpdateResp
	25, // 33: relation.RelationService.BlockUser:output_type -> relation.BlockUserResp
	27, // 34: relation.RelationService.UnblockUser:output_type -> relation.UnblockUserResp
	30, // 35: relation.RelationService.GetBlockedUsers:output_type -> relation.GetBlockedUsersResp
	32, // 36: relation.RelationService.IsFriend:output_type -> relation.IsFriendResp
	34, // 37: relation.RelationService.IsBlack:output_type -> relation.IsBlackResp
	22, // [22:38] is the sub-list for method output_type
	6,  // [6:22] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_relation_proto_init() }
func file_relation_proto_init() {
	if File_relation_proto != nil {
		return
	}
	file_relation_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relation_proto_rawDesc), len(file_relation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relation_proto_goTypes,
		DependencyIndexes: file_relation_proto_depIdxs,
		MessageInfos:      file_relation_proto_msgTypes,
	}.Build()
	File_relation_proto = out.File
	file_relation_proto_goTypes = nil
	file_relation_proto_depIdxs = nil
}
