// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: message.proto

package messagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OfflinePush carries the offline push payload for a message.
type OfflinePush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Ex            string                 `protobuf:"bytes,3,opt,name=ex,proto3" json:"ex,omitempty"`
	IosSound      string                 `protobuf:"bytes,4,opt,name=ios_sound,json=iosSound,proto3" json:"ios_sound,omitempty"`
	IosBadgeCount bool                   `protobuf:"varint,5,opt,name=ios_badge_count,json=iosBadgeCount,proto3" json:"ios_badge_count,omitempty"`
	SignalInfo    string                 `protobuf:"bytes,6,opt,name=signal_info,json=signalInfo,proto3" json:"signal_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfflinePush) Reset() {
	*x = OfflinePush{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflinePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflinePush) ProtoMessage() {}

func (x *OfflinePush) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflinePush.ProtoReflect.Descriptor instead.
func (*OfflinePush) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *OfflinePush) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *OfflinePush) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *OfflinePush) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

func (x *OfflinePush) GetIosSound() string {
	if x != nil {
		return x.IosSound
	}
	return ""
}

func (x *OfflinePush) GetIosBadgeCount() bool {
	if x != nil {
		return x.IosBadgeCount
	}
	return false
}

func (x *OfflinePush) GetSignalInfo() string {
	if x != nil {
		return x.SignalInfo
	}
	return ""
}

// RevokeInfo records who/when revoked a message.
type RevokeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          int32                  `protobuf:"varint,1,opt,name=role,proto3" json:"role,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Time          int64                  `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeInfo) Reset() {
	*x = RevokeInfo{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeInfo) ProtoMessage() {}

func (x *RevokeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeInfo.ProtoReflect.Descriptor instead.
func (*RevokeInfo) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *RevokeInfo) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *RevokeInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RevokeInfo) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

// MsgData is a single chat message. It maps 1:1 to the msg_info storage model.
type MsgData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientMsgId    string                 `protobuf:"bytes,1,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"` // client-generated id, used for idempotency
	ServerMsgId    string                 `protobuf:"bytes,2,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"` // server-generated id
	ConversationId string                 `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SendId         string                 `protobuf:"bytes,4,opt,name=send_id,json=sendId,proto3" json:"send_id,omitempty"`                 // sender user id
	RecvId         string                 `protobuf:"bytes,5,opt,name=recv_id,json=recvId,proto3" json:"recv_id,omitempty"`                 // peer user id (single chat)
	GroupId        string                 `protobuf:"bytes,6,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`              // group id (group chat)
	SessionType    int32                  `protobuf:"varint,7,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"` // 1=single 2=group
	MsgFrom        int32                  `protobuf:"varint,8,opt,name=msg_from,json=msgFrom,proto3" json:"msg_from,omitempty"`
	ContentType    int32                  `protobuf:"varint,9,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // text/image/voice/file/...
	Content        string                 `protobuf:"bytes,10,opt,name=content,proto3" json:"content,omitempty"`                            // json payload defined by caller
	Seq            int64                  `protobuf:"varint,11,opt,name=seq,proto3" json:"seq,omitempty"`                                   // per-conversation increasing sequence
	SendTime       int64                  `protobuf:"varint,12,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`         // epoch millis
	Status         int32                  `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`                             // 0=normal 1=revoked
	Ex             string                 `protobuf:"bytes,14,opt,name=ex,proto3" json:"ex,omitempty"`
	// Deprecated: Marked as deprecated in message.proto.
	IsRead bool `protobuf:"varint,15,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"` // use the per-user seq_user.read_seq cursor
	// ---- extended fields (OpenIM MsgDataModel) ----
	SenderPlatformId int32        `protobuf:"varint,16,opt,name=sender_platform_id,json=senderPlatformId,proto3" json:"sender_platform_id,omitempty"`
	SenderNickname   string       `protobuf:"bytes,17,opt,name=sender_nickname,json=senderNickname,proto3" json:"sender_nickname,omitempty"`
	SenderFaceUrl    string       `protobuf:"bytes,18,opt,name=sender_face_url,json=senderFaceUrl,proto3" json:"sender_face_url,omitempty"`
	Options          string       `protobuf:"bytes,19,opt,name=options,proto3" json:"options,omitempty"` // json map[string]bool
	AtUserIdList     []string     `protobuf:"bytes,20,rep,name=at_user_id_list,json=atUserIdList,proto3" json:"at_user_id_list,omitempty"`
	AttachedInfo     string       `protobuf:"bytes,21,opt,name=attached_info,json=attachedInfo,proto3" json:"attached_info,omitempty"`
	OfflinePush      *OfflinePush `protobuf:"bytes,22,opt,name=offline_push,json=offlinePush,proto3" json:"offline_push,omitempty"`
	Revoke           *RevokeInfo  `protobuf:"bytes,23,opt,name=revoke,proto3" json:"revoke,omitempty"`
	// server-assigned, returned to the caller
	DocId    string `protobuf:"bytes,24,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`           // conversationID:docIndex (batching)
	MsgIndex int32  `protobuf:"varint,25,opt,name=msg_index,json=msgIndex,proto3" json:"msg_index,omitempty"` // index within the document
	// Deprecated: clients should not rely on this. Single chat falls back to
	// recv_id; group chat recipients are resolved server-side via
	// group.GetGroupMemberUserIDs (OpenIM-aligned).
	//
	// Deprecated: Marked as deprecated in message.proto.
	RecvUserIds   []string `protobuf:"bytes,26,rep,name=recv_user_ids,json=recvUserIds,proto3" json:"recv_user_ids,omitempty"`
	CreateTime    int64    `protobuf:"varint,27,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgData) Reset() {
	*x = MsgData{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgData) ProtoMessage() {}

func (x *MsgData) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgData.ProtoReflect.Descriptor instead.
func (*MsgData) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *MsgData) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *MsgData) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

func (x *MsgData) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MsgData) GetSendId() string {
	if x != nil {
		return x.SendId
	}
	return ""
}

func (x *MsgData) GetRecvId() string {
	if x != nil {
		return x.RecvId
	}
	return ""
}

func (x *MsgData) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *MsgData) GetSessionType() int32 {
	if x != nil {
		return x.SessionType
	}
	return 0
}

func (x *MsgData) GetMsgFrom() int32 {
	if x != nil {
		return x.MsgFrom
	}
	return 0
}

func (x *MsgData) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *MsgData) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MsgData) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MsgData) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *MsgData) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MsgData) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

// Deprecated: Marked as deprecated in message.proto.
func (x *MsgData) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *MsgData) GetSenderPlatformId() int32 {
	if x != nil {
		return x.SenderPlatformId
	}
	return 0
}

func (x *MsgData) GetSenderNickname() string {
	if x != nil {
		return x.SenderNickname
	}
	return ""
}

func (x *MsgData) GetSenderFaceUrl() string {
	if x != nil {
		return x.SenderFaceUrl
	}
	return ""
}

func (x *MsgData) GetOptions() string {
	if x != nil {
		return x.Options
	}
	return ""
}

func (x *MsgData) GetAtUserIdList() []string {
	if x != nil {
		return x.AtUserIdList
	}
	return nil
}

func (x *MsgData) GetAttachedInfo() string {
	if x != nil {
		return x.AttachedInfo
	}
	return ""
}

func (x *MsgData) GetOfflinePush() *OfflinePush {
	if x != nil {
		return x.OfflinePush
	}
	return nil
}

func (x *MsgData) GetRevoke() *RevokeInfo {
	if x != nil {
		return x.Revoke
	}
	return nil
}

func (x *MsgData) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *MsgData) GetMsgIndex() int32 {
	if x != nil {
		return x.MsgIndex
	}
	return 0
}

// Deprecated: Marked as deprecated in message.proto.
func (x *MsgData) GetRecvUserIds() []string {
	if x != nil {
		return x.RecvUserIds
	}
	return nil
}

func (x *MsgData) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

// --------------- SendMsg ---------------
type SendMsgReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgData       *MsgData               `protobuf:"bytes,1,opt,name=msg_data,json=msgData,proto3" json:"msg_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMsgReq) Reset() {
	*x = SendMsgReq{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgReq) ProtoMessage() {}

func (x *SendMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgReq.ProtoReflect.Descriptor instead.
func (*SendMsgReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *SendMsgReq) GetMsgData() *MsgData {
	if x != nil {
		return x.MsgData
	}
	return nil
}

type SendMsgResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerMsgId   string                 `protobuf:"bytes,1,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	Seq           int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	SendTime      int64                  `protobuf:"varint,3,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	DocId         string                 `protobuf:"bytes,4,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	MsgIndex      int32                  `protobuf:"varint,5,opt,name=msg_index,json=msgIndex,proto3" json:"msg_index,omitempty"`
	ClientMsgId   string                 `protobuf:"bytes,6,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"` // 对齐 OpenIM SendMsgResp.clientMsgID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMsgResp) Reset() {
	*x = SendMsgResp{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgResp) ProtoMessage() {}

func (x *SendMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgResp.ProtoReflect.Descriptor instead.
func (*SendMsgResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *SendMsgResp) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

func (x *SendMsgResp) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SendMsgResp) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *SendMsgResp) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *SendMsgResp) GetMsgIndex() int32 {
	if x != nil {
		return x.MsgIndex
	}
	return 0
}

func (x *SendMsgResp) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

// --------------- GetHistoryMessages ---------------
// `seq` is the anchor. order=0 (newest->oldest, default) returns messages with
// seq < anchor; order=1 (oldest->newest) returns messages with seq > anchor.
// anchor=0 with order=0 returns the latest page.
type GetHistoryMessagesReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Seq            int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Limit          int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Order          int32                  `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetHistoryMessagesReq) Reset() {
	*x = GetHistoryMessagesReq{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryMessagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryMessagesReq) ProtoMessage() {}

func (x *GetHistoryMessagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryMessagesReq.ProtoReflect.Descriptor instead.
func (*GetHistoryMessagesReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *GetHistoryMessagesReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetHistoryMessagesReq) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GetHistoryMessagesReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetHistoryMessagesReq) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type GetHistoryMessagesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgData       []*MsgData             `protobuf:"bytes,1,rep,name=msg_data,json=msgData,proto3" json:"msg_data,omitempty"`
	IsEnd         bool                   `protobuf:"varint,2,opt,name=is_end,json=isEnd,proto3" json:"is_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryMessagesResp) Reset() {
	*x = GetHistoryMessagesResp{}
	mi := &file_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryMessagesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryMessagesResp) ProtoMessage() {}

func (x *GetHistoryMessagesResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryMessagesResp.ProtoReflect.Descriptor instead.
func (*GetHistoryMessagesResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *GetHistoryMessagesResp) GetMsgData() []*MsgData {
	if x != nil {
		return x.MsgData
	}
	return nil
}

func (x *GetHistoryMessagesResp) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

// --------------- GetMessagesBySeq ---------------
type GetMessagesBySeqReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Seqs           []int64                `protobuf:"varint,2,rep,packed,name=seqs,proto3" json:"seqs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMessagesBySeqReq) Reset() {
	*x = GetMessagesBySeqReq{}
	mi := &file_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesBySeqReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesBySeqReq) ProtoMessage() {}

func (x *GetMessagesBySeqReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesBySeqReq.ProtoReflect.Descriptor instead.
func (*GetMessagesBySeqReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

func (x *GetMessagesBySeqReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetMessagesBySeqReq) GetSeqs() []int64 {
	if x != nil {
		return x.Seqs
	}
	return nil
}

type GetMessagesBySeqResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgData       []*MsgData             `protobuf:"bytes,1,rep,name=msg_data,json=msgData,proto3" json:"msg_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesBySeqResp) Reset() {
	*x = GetMessagesBySeqResp{}
	mi := &file_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesBySeqResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesBySeqResp) ProtoMessage() {}

func (x *GetMessagesBySeqResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesBySeqResp.ProtoReflect.Descriptor instead.
func (*GetMessagesBySeqResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{8}
}

func (x *GetMessagesBySeqResp) GetMsgData() []*MsgData {
	if x != nil {
		return x.MsgData
	}
	return nil
}

// --------------- GetMessagesByClientMsgIDs ---------------
type GetMessagesByClientMsgIDsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientMsgIds  []string               `protobuf:"bytes,1,rep,name=client_msg_ids,json=clientMsgIds,proto3" json:"client_msg_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesByClientMsgIDsReq) Reset() {
	*x = GetMessagesByClientMsgIDsReq{}
	mi := &file_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesByClientMsgIDsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesByClientMsgIDsReq) ProtoMessage() {}

func (x *GetMessagesByClientMsgIDsReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesByClientMsgIDsReq.ProtoReflect.Descriptor instead.
func (*GetMessagesByClientMsgIDsReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{9}
}

func (x *GetMessagesByClientMsgIDsReq) GetClientMsgIds() []string {
	if x != nil {
		return x.ClientMsgIds
	}
	return nil
}

type GetMessagesByClientMsgIDsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgData       []*MsgData             `protobuf:"bytes,1,rep,name=msg_data,json=msgData,proto3" json:"msg_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesByClientMsgIDsResp) Reset() {
	*x = GetMessagesByClientMsgIDsResp{}
	mi := &file_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesByClientMsgIDsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesByClientMsgIDsResp) ProtoMessage() {}

func (x *GetMessagesByClientMsgIDsResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesByClientMsgIDsResp.ProtoReflect.Descriptor instead.
func (*GetMessagesByClientMsgIDsResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{10}
}

func (x *GetMessagesByClientMsgIDsResp) GetMsgData() []*MsgData {
	if x != nil {
		return x.MsgData
	}
	return nil
}

// --------------- RevokeMsg ---------------
type RevokeMsgReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ClientMsgId    string                 `protobuf:"bytes,2,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	// Deprecated: Marked as deprecated in message.proto.
	SendId string `protobuf:"bytes,3,opt,name=send_id,json=sendId,proto3" json:"send_id,omitempty"`
	// Deprecated: Marked as deprecated in message.proto.
	RevokeRole int32 `protobuf:"varint,4,opt,name=revoke_role,json=revokeRole,proto3" json:"revoke_role,omitempty"`
	// Deprecated: Marked as deprecated in message.proto.
	RevokeNickname string `protobuf:"bytes,5,opt,name=revoke_nickname,json=revokeNickname,proto3" json:"revoke_nickname,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RevokeMsgReq) Reset() {
	*x = RevokeMsgReq{}
	mi := &file_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeMsgReq) ProtoMessage() {}

func (x *RevokeMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeMsgReq.ProtoReflect.Descriptor instead.
func (*RevokeMsgReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{11}
}

func (x *RevokeMsgReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *RevokeMsgReq) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

// Deprecated: Marked as deprecated in message.proto.
func (x *RevokeMsgReq) GetSendId() string {
	if x != nil {
		return x.SendId
	}
	return ""
}

// Deprecated: Marked as deprecated in message.proto.
func (x *RevokeMsgReq) GetRevokeRole() int32 {
	if x != nil {
		return x.RevokeRole
	}
	return 0
}

// Deprecated: Marked as deprecated in message.proto.
func (x *RevokeMsgReq) GetRevokeNickname() string {
	if x != nil {
		return x.RevokeNickname
	}
	return ""
}

type RevokeMsgResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeMsgResp) Reset() {
	*x = RevokeMsgResp{}
	mi := &file_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeMsgResp) ProtoMessage() {}

func (x *RevokeMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeMsgResp.ProtoReflect.Descriptor instead.
func (*RevokeMsgResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{12}
}

// --------------- MarkMsgsAsRead ---------------
type MarkMsgsAsReadReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	// Deprecated: Marked as deprecated in message.proto.
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Seq           int64  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"` // mark all messages with seq <= this as read
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkMsgsAsReadReq) Reset() {
	*x = MarkMsgsAsReadReq{}
	mi := &file_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkMsgsAsReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkMsgsAsReadReq) ProtoMessage() {}

func (x *MarkMsgsAsReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkMsgsAsReadReq.ProtoReflect.Descriptor instead.
func (*MarkMsgsAsReadReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{13}
}

func (x *MarkMsgsAsReadReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

// Deprecated: Marked as deprecated in message.proto.
func (x *MarkMsgsAsReadReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MarkMsgsAsReadReq) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type MarkMsgsAsReadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkMsgsAsReadResp) Reset() {
	*x = MarkMsgsAsReadResp{}
	mi := &file_message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkMsgsAsReadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkMsgsAsReadResp) ProtoMessage() {}

func (x *MarkMsgsAsReadResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkMsgsAsReadResp.ProtoReflect.Descriptor instead.
func (*MarkMsgsAsReadResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{14}
}

// --------------- DeleteMsgs ---------------
type DeleteMsgsReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Seqs           []int64                `protobuf:"varint,2,rep,packed,name=seqs,proto3" json:"seqs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteMsgsReq) Reset() {
	*x = DeleteMsgsReq{}
	mi := &file_message_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMsgsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMsgsReq) ProtoMessage() {}

func (x *DeleteMsgsReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMsgsReq.ProtoReflect.Descriptor instead.
func (*DeleteMsgsReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteMsgsReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *DeleteMsgsReq) GetSeqs() []int64 {
	if x != nil {
		return x.Seqs
	}
	return nil
}

type DeleteMsgsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMsgsResp) Reset() {
	*x = DeleteMsgsResp{}
	mi := &file_message_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMsgsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMsgsResp) ProtoMessage() {}

func (x *DeleteMsgsResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMsgsResp.ProtoReflect.Descriptor instead.
func (*DeleteMsgsResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{16}
}

// --------------- GetMaxSeq ---------------
type GetMaxSeqReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConversationIds []string               `protobuf:"bytes,1,rep,name=conversation_ids,json=conversationIds,proto3" json:"conversation_ids,omitempty"` // empty = all seq_user rows for caller
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetMaxSeqReq) Reset() {
	*x = GetMaxSeqReq{}
	mi := &file_message_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMaxSeqReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaxSeqReq) ProtoMessage() {}

func (x *GetMaxSeqReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaxSeqReq.ProtoReflect.Descriptor instead.
func (*GetMaxSeqReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{17}
}

func (x *GetMaxSeqReq) GetConversationIds() []string {
	if x != nil {
		return x.ConversationIds
	}
	return nil
}

type GetMaxSeqResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxSeqs       map[string]int64       `protobuf:"bytes,1,rep,name=max_seqs,json=maxSeqs,proto3" json:"max_seqs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // conversation_id → max_seq
	MinSeqs       map[string]int64       `protobuf:"bytes,2,rep,name=min_seqs,json=minSeqs,proto3" json:"min_seqs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // conversation_id → min_seq（对齐 OpenIM）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMaxSeqResp) Reset() {
	*x = GetMaxSeqResp{}
	mi := &file_message_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMaxSeqResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaxSeqResp) ProtoMessage() {}

func (x *GetMaxSeqResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaxSeqResp.ProtoReflect.Descriptor instead.
func (*GetMaxSeqResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{18}
}

func (x *GetMaxSeqResp) GetMaxSeqs() map[string]int64 {
	if x != nil {
		return x.MaxSeqs
	}
	return nil
}

func (x *GetMaxSeqResp) GetMinSeqs() map[string]int64 {
	if x != nil {
		return x.MinSeqs
	}
	return nil
}

// --------------- GetConversationsHasReadAndMaxSeq ---------------
type Seqs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxSeq        int64                  `protobuf:"varint,1,opt,name=max_seq,json=maxSeq,proto3" json:"max_seq,omitempty"`
	HasReadSeq    int64                  `protobuf:"varint,2,opt,name=has_read_seq,json=hasReadSeq,proto3" json:"has_read_seq,omitempty"`
	MaxSeqTime    int64                  `protobuf:"varint,3,opt,name=max_seq_time,json=maxSeqTime,proto3" json:"max_seq_time,omitempty"` // max_seq 对应消息的 send_time（ms），无则 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seqs) Reset() {
	*x = Seqs{}
	mi := &file_message_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seqs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seqs) ProtoMessage() {}

func (x *Seqs) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seqs.ProtoReflect.Descriptor instead.
func (*Seqs) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{19}
}

func (x *Seqs) GetMaxSeq() int64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

func (x *Seqs) GetHasReadSeq() int64 {
	if x != nil {
		return x.HasReadSeq
	}
	return 0
}

func (x *Seqs) GetMaxSeqTime() int64 {
	if x != nil {
		return x.MaxSeqTime
	}
	return 0
}

type GetConversationsHasReadAndMaxSeqReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConversationIds []string               `protobuf:"bytes,1,rep,name=conversation_ids,json=conversationIds,proto3" json:"conversation_ids,omitempty"` // empty = all
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetConversationsHasReadAndMaxSeqReq) Reset() {
	*x = GetConversationsHasReadAndMaxSeqReq{}
	mi := &file_message_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationsHasReadAndMaxSeqReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationsHasReadAndMaxSeqReq) ProtoMessage() {}

func (x *GetConversationsHasReadAndMaxSeqReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationsHasReadAndMaxSeqReq.ProtoReflect.Descriptor instead.
func (*GetConversationsHasReadAndMaxSeqReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{20}
}

func (x *GetConversationsHasReadAndMaxSeqReq) GetConversationIds() []string {
	if x != nil {
		return x.ConversationIds
	}
	return nil
}

type GetConversationsHasReadAndMaxSeqResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seqs          map[string]*Seqs       `protobuf:"bytes,1,rep,name=seqs,proto3" json:"seqs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationsHasReadAndMaxSeqResp) Reset() {
	*x = GetConversationsHasReadAndMaxSeqResp{}
	mi := &file_message_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationsHasReadAndMaxSeqResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationsHasReadAndMaxSeqResp) ProtoMessage() {}

func (x *GetConversationsHasReadAndMaxSeqResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationsHasReadAndMaxSeqResp.ProtoReflect.Descriptor instead.
func (*GetConversationsHasReadAndMaxSeqResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{21}
}

func (x *GetConversationsHasReadAndMaxSeqResp) GetSeqs() map[string]*Seqs {
	if x != nil {
		return x.Seqs
	}
	return nil
}

// --------------- GetActiveConversation (对齐 OpenIM msg.GetActiveConversation) ---------------
type GetActiveConversationReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConversationIds []string               `protobuf:"bytes,1,rep,name=conversation_ids,json=conversationIds,proto3" json:"conversation_ids,omitempty"`
	Limit           int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // 0 = 不截断；>0 时按 last_time 降序截断
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetActiveConversationReq) Reset() {
	*x = GetActiveConversationReq{}
	mi := &file_message_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveConversationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveConversationReq) ProtoMessage() {}

func (x *GetActiveConversationReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveConversationReq.ProtoReflect.Descriptor instead.
func (*GetActiveConversationReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{22}
}

func (x *GetActiveConversationReq) GetConversationIds() []string {
	if x != nil {
		return x.ConversationIds
	}
	return nil
}

func (x *GetActiveConversationReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ActiveConversation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	LastTime       int64                  `protobuf:"varint,2,opt,name=last_time,json=lastTime,proto3" json:"last_time,omitempty"` // max_seq 对应消息 send_time (ms)
	MaxSeq         int64                  `protobuf:"varint,3,opt,name=max_seq,json=maxSeq,proto3" json:"max_seq,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActiveConversation) Reset() {
	*x = ActiveConversation{}
	mi := &file_message_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveConversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveConversation) ProtoMessage() {}

func (x *ActiveConversation) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveConversation.ProtoReflect.Descriptor instead.
func (*ActiveConversation) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{23}
}

func (x *ActiveConversation) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ActiveConversation) GetLastTime() int64 {
	if x != nil {
		return x.LastTime
	}
	return 0
}

func (x *ActiveConversation) GetMaxSeq() int64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

type GetActiveConversationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*ActiveConversation  `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveConversationResp) Reset() {
	*x = GetActiveConversationResp{}
	mi := &file_message_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveConversationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveConversationResp) ProtoMessage() {}

func (x *GetActiveConversationResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveConversationResp.ProtoReflect.Descriptor instead.
func (*GetActiveConversationResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{24}
}

func (x *GetActiveConversationResp) GetConversations() []*ActiveConversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

// --------------- GetLastMessage (对齐 OpenIM msg.GetLastMessage) ---------------
type GetLastMessageReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // handler 以 JWT 用户为准覆盖
	ConversationIds []string               `protobuf:"bytes,2,rep,name=conversation_ids,json=conversationIds,proto3" json:"conversation_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetLastMessageReq) Reset() {
	*x = GetLastMessageReq{}
	mi := &file_message_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastMessageReq) ProtoMessage() {}

func (x *GetLastMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastMessageReq.ProtoReflect.Descriptor instead.
func (*GetLastMessageReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{25}
}

func (x *GetLastMessageReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetLastMessageReq) GetConversationIds() []string {
	if x != nil {
		return x.ConversationIds
	}
	return nil
}

type GetLastMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msgs          map[string]*MsgData    `protobuf:"bytes,1,rep,name=msgs,proto3" json:"msgs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // conversation_id → 最后一条对用户可见的消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastMessageResp) Reset() {
	*x = GetLastMessageResp{}
	mi := &file_message_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastMessageResp) ProtoMessage() {}

func (x *GetLastMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastMessageResp.ProtoReflect.Descriptor instead.
func (*GetLastMessageResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{26}
}

func (x *GetLastMessageResp) GetMsgs() map[string]*MsgData {
	if x != nil {
		return x.Msgs
	}
	return nil
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\amessage\"\xad\x01\n" +
	"\vOfflinePush\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\x12\x0e\n" +
	"\x02ex\x18\x03 \x01(\tR\x02ex\x12\x1b\n" +
	"\tios_sound\x18\x04 \x01(\tR\biosSound\x12&\n" +
	"\x0fios_badge_count\x18\x05 \x01(\bR\riosBadgeCount\x12\x1f\n" +
	"\vsignal_info\x18\x06 \x01(\tR\n" +
	"signalInfo\"i\n" +
	"\n" +
	"RevokeInfo\x12\x12\n" +
	"\x04role\x18\x01 \x01(\x05R\x04role\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x12\n" +
	"\x04time\x18\x04 \x01(\x03R\x04time\"\xfe\x06\n" +
	"\aMsgData\x12\"\n" +
	"\rclient_msg_id\x18\x01 \x01(\tR\vclientMsgId\x12\"\n" +
	"\rserver_msg_id\x18\x02 \x01(\tR\vserverMsgId\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\x12\x17\n" +
	"\asend_id\x18\x04 \x01(\tR\x06sendId\x12\x17\n" +
	"\arecv_id\x18\x05 \x01(\tR\x06recvId\x12\x19\n" +
	"\bgroup_id\x18\x06 \x01(\tR\agroupId\x12!\n" +
	"\fsession_type\x18\a \x01(\x05R\vsessionType\x12\x19\n" +
	"\bmsg_from\x18\b \x01(\x05R\amsgFrom\x12!\n" +
	"\fcontent_type\x18\t \x01(\x05R\vcontentType\x12\x18\n" +
	"\acontent\x18\n" +
	" \x01(\tR\acontent\x12\x10\n" +
	"\x03seq\x18\v \x01(\x03R\x03seq\x12\x1b\n" +
	"\tsend_time\x18\f \x01(\x03R\bsendTime\x12\x16\n" +
	"\x06status\x18\r \x01(\x05R\x06status\x12\x0e\n" +
	"\x02ex\x18\x0e \x01(\tR\x02ex\x12\x1b\n" +
	"\ais_read\x18\x0f \x01(\bB\x02\x18\x01R\x06isRead\x12,\n" +
	"\x12sender_platform_id\x18\x10 \x01(\x05R\x10senderPlatformId\x12'\n" +
	"\x0fsender_nickname\x18\x11 \x01(\tR\x0esenderNickname\x12&\n" +
	"\x0fsender_face_url\x18\x12 \x01(\tR\rsenderFaceUrl\x12\x18\n" +
	"\aoptions\x18\x13 \x01(\tR\aoptions\x12%\n" +
	"\x0fat_user_id_list\x18\x14 \x03(\tR\fatUserIdList\x12#\n" +
	"\rattached_info\x18\x15 \x01(\tR\fattachedInfo\x127\n" +
	"\foffline_push\x18\x16 \x01(\v2\x14.message.OfflinePushR\vofflinePush\x12+\n" +
	"\x06revoke\x18\x17 \x01(\v2\x13.message.RevokeInfoR\x06revoke\x12\x15\n" +
	"\x06doc_id\x18\x18 \x01(\tR\x05docId\x12\x1b\n" +
	"\tmsg_index\x18\x19 \x01(\x05R\bmsgIndex\x12&\n" +
	"\rrecv_user_ids\x18\x1a \x03(\tB\x02\x18\x01R\vrecvUserIds\x12\x1f\n" +
	"\vcreate_time\x18\x1b \x01(\x03R\n" +
	"createTime\"9\n" +
	"\n" +
	"SendMsgReq\x12+\n" +
	"\bmsg_data\x18\x01 \x01(\v2\x10.message.MsgDataR\amsgData\"\xb8\x01\n" +
	"\vSendMsgResp\x12\"\n" +
	"\rserver_msg_id\x18\x01 \x01(\tR\vserverMsgId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12\x1b\n" +
	"\tsend_time\x18\x03 \x01(\x03R\bsendTime\x12\x15\n" +
	"\x06doc_id\x18\x04 \x01(\tR\x05docId\x12\x1b\n" +
	"\tmsg_index\x18\x05 \x01(\x05R\bmsgIndex\x12\"\n" +
	"\rclient_msg_id\x18\x06 \x01(\tR\vclientMsgId\"~\n" +
	"\x15GetHistoryMessagesReq\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05order\x18\x04 \x01(\x05R\x05order\"\\\n" +
	"\x16GetHistoryMessagesResp\x12+\n" +
	"\bmsg_data\x18\x01 \x03(\v2\x10.message.MsgDataR\amsgData\x12\x15\n" +
	"\x06is_end\x18\x02 \x01(\bR\x05isEnd\"R\n" +
	"\x13GetMessagesBySeqReq\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x12\n" +
	"\x04seqs\x18\x02 \x03(\x03R\x04seqs\"C\n" +
	"\x14GetMessagesBySeqResp\x12+\n" +
	"\bmsg_data\x18\x01 \x03(\v2\x10.message.MsgDataR\amsgData\"D\n" +
	"\x1cGetMessagesByClientMsgIDsReq\x12$\n" +
	"\x0eclient_msg_ids\x18\x01 \x03(\tR\fclientMsgIds\"L\n" +
	"\x1dGetMessagesByClientMsgIDsResp\x12+\n" +
	"\bmsg_data\x18\x01 \x03(\v2\x10.message.MsgDataR\amsgData\"\xca\x01\n" +
	"\fRevokeMsgReq\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\"\n" +
	"\rclient_msg_id\x18\x02 \x01(\tR\vclientMsgId\x12\x1b\n" +
	"\asend_id\x18\x03 \x01(\tB\x02\x18\x01R\x06sendId\x12#\n" +
	"\vrevoke_role\x18\x04 \x01(\x05B\x02\x18\x01R\n" +
	"revokeRole\x12+\n" +
	"\x0frevoke_nickname\x18\x05 \x01(\tB\x02\x18\x01R\x0erevokeNickname\"\x0f\n" +
	"\rRevokeMsgResp\"k\n" +
	"\x11MarkMsgsAsReadReq\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\auser_id\x18\x02 \x01(\tB\x02\x18\x01R\x06userId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\"\x14\n" +
	"\x12MarkMsgsAsReadResp\"L\n" +
	"\rDeleteMsgsReq\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x12\n" +
	"\x04seqs\x18\x02 \x03(\x03R\x04seqs\"\x10\n" +
	"\x0eDeleteMsgsResp\"9\n" +
	"\fGetMaxSeqReq\x12)\n" +
	"\x10conversation_ids\x18\x01 \x03(\tR\x0fconversationIds\"\x87\x02\n" +
	"\rGetMaxSeqResp\x12>\n" +
	"\bmax_seqs\x18\x01 \x03(\v2#.message.GetMaxSeqResp.MaxSeqsEntryR\amaxSeqs\x12>\n" +
	"\bmin_seqs\x18\x02 \x03(\v2#.message.GetMaxSeqResp.MinSeqsEntryR\aminSeqs\x1a:\n" +
	"\fMaxSeqsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a:\n" +
	"\fMinSeqsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"c\n" +
	"\x04Seqs\x12\x17\n" +
	"\amax_seq\x18\x01 \x01(\x03R\x06maxSeq\x12 \n" +
	"\fhas_read_seq\x18\x02 \x01(\x03R\n" +
	"hasReadSeq\x12 \n" +
	"\fmax_seq_time\x18\x03 \x01(\x03R\n" +
	"maxSeqTime\"P\n" +
	"#GetConversationsHasReadAndMaxSeqReq\x12)\n" +
	"\x10conversation_ids\x18\x01 \x03(\tR\x0fconversationIds\"\xbb\x01\n" +
	"$GetConversationsHasReadAndMaxSeqResp\x12K\n" +
	"\x04seqs\x18\x01 \x03(\v27.message.GetConversationsHasReadAndMaxSeqResp.SeqsEntryR\x04seqs\x1aF\n" +
	"\tSeqsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.message.SeqsR\x05value:\x028\x01\"[\n" +
	"\x18GetActiveConversationReq\x12)\n" +
	"\x10conversation_ids\x18\x01 \x03(\tR\x0fconversationIds\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"s\n" +
	"\x12ActiveConversation\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tlast_time\x18\x02 \x01(\x03R\blastTime\x12\x17\n" +
	"\amax_seq\x18\x03 \x01(\x03R\x06maxSeq\"^\n" +
	"\x19GetActiveConversationResp\x12A\n" +
	"\rconversations\x18\x01 \x03(\v2\x1b.message.ActiveConversationR\rconversations\"W\n" +
	"\x11GetLastMessageReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12)\n" +
	"\x10conversation_ids\x18\x02 \x03(\tR\x0fconversationIds\"\x9a\x01\n" +
	"\x12GetLastMessageResp\x129\n" +
	"\x04msgs\x18\x01 \x03(\v2%.message.GetLastMessageResp.MsgsEntryR\x04msgs\x1aI\n" +
	"\tMsgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.message.MsgDataR\x05value:\x028\x012\x81\a\n" +
	"\amessage\x124\n" +
	"\aSendMsg\x12\x13.message.SendMsgReq\x1a\x14.message.SendMsgResp\x12U\n" +
	"\x12GetHistoryMessages\x12\x1e.message.GetHistoryMessagesReq\x1a\x1f.message.GetHistoryMessagesResp\x12O\n" +
	"\x10GetMessagesBySeq\x12\x1c.message.GetMessagesBySeqReq\x1a\x1d.message.GetMessagesBySeqResp\x12j\n" +
	"\x19GetMessagesByClientMsgIDs\x12%.message.GetMessagesByClientMsgIDsReq\x1a&.message.GetMessagesByClientMsgIDsResp\x12:\n" +
	"\tRevokeMsg\x12\x15.message.RevokeMsgReq\x1a\x16.message.RevokeMsgResp\x12I\n" +
	"\x0eMarkMsgsAsRead\x12\x1a.message.MarkMsgsAsReadReq\x1a\x1b.message.MarkMsgsAsReadResp\x12=\n" +
	"\n" +
	"DeleteMsgs\x12\x16.message.DeleteMsgsReq\x1a\x17.message.DeleteMsgsResp\x12:\n" +
	"\tGetMaxSeq\x12\x15.message.GetMaxSeqReq\x1a\x16.message.GetMaxSeqResp\x12\x7f\n" +
	" GetConversationsHasReadAndMaxSeq\x12,.message.GetConversationsHasReadAndMaxSeqReq\x1a-.message.GetConversationsHasReadAndMaxSeqResp\x12^\n" +
	"\x15GetActiveConversation\x12!.message.GetActiveConversationReq\x1a\".message.GetActiveConversationResp\x12I\n" +
	"\x0eGetLastMessage\x12\x1a.message.GetLastMessageReq\x1a\x1b.message.GetLastMessageRespB\x16Z\x14SuIM/proto/messagepbb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_message_proto_goTypes = []any{
	(*OfflinePush)(nil),                          // 0: message.OfflinePush
	(*RevokeInfo)(nil),                           // 1: message.RevokeInfo
	(*MsgData)(nil),                              // 2: message.MsgData
	(*SendMsgReq)(nil),                           // 3: message.SendMsgReq
	(*SendMsgResp)(nil),                          // 4: message.SendMsgResp
	(*GetHistoryMessagesReq)(nil),                // 5: message.GetHistoryMessagesReq
	(*GetHistoryMessagesResp)(nil),               // 6: message.GetHistoryMessagesResp
	(*GetMessagesBySeqReq)(nil),                  // 7: message.GetMessagesBySeqReq
	(*GetMessagesBySeqResp)(nil),                 // 8: message.GetMessagesBySeqResp
	(*GetMessagesByClientMsgIDsReq)(nil),         // 9: message.GetMessagesByClientMsgIDsReq
	(*GetMessagesByClientMsgIDsResp)(nil),        // 10: message.GetMessagesByClientMsgIDsResp
	(*RevokeMsgReq)(nil),                         // 11: message.RevokeMsgReq
	(*RevokeMsgResp)(nil),                        // 12: message.RevokeMsgResp
	(*MarkMsgsAsReadReq)(nil),                    // 13: message.MarkMsgsAsReadReq
	(*MarkMsgsAsReadResp)(nil),                   // 14: message.MarkMsgsAsReadResp
	(*DeleteMsgsReq)(nil),                        // 15: message.DeleteMsgsReq
	(*DeleteMsgsResp)(nil),                       // 16: message.DeleteMsgsResp
	(*GetMaxSeqReq)(nil),                         // 17: message.GetMaxSeqReq
	(*GetMaxSeqResp)(nil),                        // 18: message.GetMaxSeqResp
	(*Seqs)(nil),                                 // 19: message.Seqs
	(*GetConversationsHasReadAndMaxSeqReq)(nil),  // 20: message.GetConversationsHasReadAndMaxSeqReq
	(*GetConversationsHasReadAndMaxSeqResp)(nil), // 21: message.GetConversationsHasReadAndMaxSeqResp
	(*GetActiveConversationReq)(nil),             // 22: message.GetActiveConversationReq
	(*ActiveConversation)(nil),                   // 23: message.ActiveConversation
	(*GetActiveConversationResp)(nil),            // 24: message.GetActiveConversationResp
	(*GetLastMessageReq)(nil),                    // 25: message.GetLastMessageReq
	(*GetLastMessageResp)(nil),                   // 26: message.GetLastMessageResp
	nil,                                          // 27: message.GetMaxSeqResp.MaxSeqsEntry
	nil,                                          // 28: message.GetMaxSeqResp.MinSeqsEntry
	nil,                                          // 29: message.GetConversationsHasReadAndMaxSeqResp.SeqsEntry
	nil,                                          // 30: message.GetLastMessageResp.MsgsEntry
}
var file_message_proto_depIdxs = []int32{
	0,  // 0: message.MsgData.offline_push:type_name -> message.OfflinePush
	1,  // 1: message.MsgData.revoke:type_name -> message.RevokeInfo
	2,  // 2: message.SendMsgReq.msg_data:type_name -> message.MsgData
	2,  // 3: message.GetHistoryMessagesResp.msg_data:type_name -> message.MsgData
	2,  // 4: message.GetMessagesBySeqResp.msg_data:type_name -> message.MsgData
	2,  // 5: message.GetMessagesByClientMsgIDsResp.msg_data:type_name -> message.MsgData
	27, // 6: message.GetMaxSeqResp.max_seqs:type_name -> message.GetMaxSeqResp.MaxSeqsEntry
	28, // 7: message.GetMaxSeqResp.min_seqs:type_name -> message.GetMaxSeqResp.MinSeqsEntry
	29, // 8: message.GetConversationsHasReadAndMaxSeqResp.seqs:type_name -> message.GetConversationsHasReadAndMaxSeqResp.SeqsEntry
	23, // 9: message.GetActiveConversationResp.conversations:type_name -> message.ActiveConversation
	30, // 10: message.GetLastMessageResp.msgs:type_name -> message.GetLastMessageResp.MsgsEntry
	19, // 11: message.GetConversationsHasReadAndMaxSeqResp.SeqsEntry.value:type_name -> message.Seqs
	2,  // 12: message.GetLastMessageResp.MsgsEntry.value:type_name -> message.MsgData
	3,  // 13: message.message.SendMsg:input_type -> message.SendMsgReq
	5,  // 14: message.message.GetHistoryMessages:input_type -> message.GetHistoryMessagesReq
	7,  // 15: message.message.GetMessagesBySeq:input_type -> message.GetMessagesBySeqReq
	9,  // 16: message.message.GetMessagesByClientMsgIDs:input_type -> message.GetMessagesByClientMsgIDsReq
	11, // 17: message.message.RevokeMsg:input_type -> message.RevokeMsgReq
	13, // 18: message.message.MarkMsgsAsRead:input_type -> message.MarkMsgsAsReadReq
	15, // 19: message.message.DeleteMsgs:input_type -> message.DeleteMsgsReq
	17, // 20: message.message.GetMaxSeq:input_type -> message.GetMaxSeqReq
	20, // 21: message.message.GetConversationsHasReadAndMaxSeq:input_type -> message.GetConversationsHasReadAndMaxSeqReq
	22, // 22: message.message.GetActiveConversation:input_type -> message.GetActiveConversationReq
	25, // 23: message.message.GetLastMessage:input_type -> message.GetLastMessageReq
	4,  // 24: message.message.SendMsg:output_type -> message.SendMsgResp
	6,  // 25: message.message.GetHistoryMessages:output_type -> message.GetHistoryMessagesResp
	8,  // 26: message.message.GetMessagesBySeq:output_type -> message.GetMessagesBySeqResp
	10, // 27: message.message.GetMessagesByClientMsgIDs:output_type -> message.GetMessagesByClientMsgIDsResp
	12, // 28: message.message.RevokeMsg:output_type -> message.RevokeMsgResp
	14, // 29: message.message.MarkMsgsAsRead:output_type -> message.MarkMsgsAsReadResp
	16, // 30: message.message.DeleteMsgs:output_type -> message.DeleteMsgsResp
	18, // 31: message.message.GetMaxSeq:output_type -> message.GetMaxSeqResp
	21, // 32: message.message.GetConversationsHasReadAndMaxSeq:output_type -> message.GetConversationsHasReadAndMaxSeqResp
	24, // 33: message.message.GetActiveConversation:output_type -> message.GetActiveConversationResp
	26, // 34: message.message.GetLastMessage:output_type -> message.GetLastMessageResp
	24, // [24:35] is the sub-list for method output_type
	13, // [13:24] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
